### ISSUE TITLE
undefined method `klass' for nil:NilClass

### ISSUE THREAD

**Issue by Olli** [railsadminteam/rails_admin#1183]
I got this error on 
rails_admin-0.0.3/app/views/rails_admin/main/index.html.haml where line #13 raised: 

``` text
activerecord (3.2.3) lib/active_record/reflection.rb:385:in `block in source_reflection'
activerecord (3.2.3) lib/active_record/reflection.rb:385:in `collect'
activerecord (3.2.3) lib/active_record/reflection.rb:385:in `source_reflection'
activerecord (3.2.3) lib/active_record/reflection.rb:375:in `rescue in foreign_key'
activerecord (3.2.3) lib/active_record/reflection.rb:373:in `foreign_key'
rails_admin (0.0.3) lib/rails_admin/adapters/active_record.rb:253:in `association_foreign_key_lookup'
rails_admin (0.0.3) lib/rails_admin/adapters/active_record.rb:65:in `block in associations'
rails_admin (0.0.3) lib/rails_admin/adapters/active_record.rb:58:in `map'
rails_admin (0.0.3) lib/rails_admin/adapters/active_record.rb:58:in `associations'
rails_admin (0.0.3) lib/rails_admin/abstract_model.rb:29:in `block (2 levels) in polymorphic_parents'
rails_admin (0.0.3) lib/rails_admin/abstract_model.rb:28:in `each'
rails_admin (0.0.3) lib/rails_admin/abstract_model.rb:28:in `block in polymorphic_parents'
rails_admin (0.0.3) lib/rails_admin/abstract_model.rb:27:in `tap'
rails_admin (0.0.3) lib/rails_admin/abstract_model.rb:27:in `polymorphic_parents'
rails_admin (0.0.3) lib/rails_admin/adapters/active_record.rb:216:in `association_model_lookup'
rails_admin (0.0.3) lib/rails_admin/adapters/active_record.rb:63:in `block (2 levels) in associations'
rails_admin (0.0.3) lib/rails_admin/config/fields/types/polymorphic_association.rb:49:in `call'
rails_admin (0.0.3) lib/rails_admin/config/fields/types/polymorphic_association.rb:49:in `associated_model_config'
rails_admin (0.0.3) lib/rails_admin/config/fields/types/polymorphic_association.rb:19:in `block in <class:PolymorphicAssociation>'
rails_admin (0.0.3) lib/rails_admin/config/configurable.rb:68:in `instance_eval'
rails_admin (0.0.3) lib/rails_admin/config/configurable.rb:68:in `block in register_instance_option'
rails_admin (0.0.3) lib/rails_admin/config/configurable.rb:42:in `block in register_instance_option'
rails_admin (0.0.3) lib/rails_admin/config/proxyable/proxy.rb:31:in `method_missing'
rails_admin (0.0.3) lib/rails_admin/config/has_fields.rb:113:in `select'
rails_admin (0.0.3) lib/rails_admin/config/has_fields.rb:113:in `visible_fields'
rails_admin (0.0.3) lib/rails_admin/config/proxyable/proxy.rb:31:in `method_missing'
rails_admin (0.0.3) app/views/rails_admin/main/index.html.haml:13:in `__home_oli__rvm_gems_ruby_______p____global_gems_rails_admin_______app_views_rails_admin_main_index_html_haml__367596137_89088280'
```

**Comment by matisoffn** [comment]
I had an association in another model that wasn't configured properly on the model it was associated to, solved this, and the error in RA went away.  Thanks.

**Comment by hayesgm** [comment]
Just hit this. It would be great to catch this error and report "You may have an invalid assoication in <model>" error instead.

**Comment by apanzerj** [comment]
If there is one thing rails admin has taught me, it is that I'm bad at Associations. During this project, Rails_Admin has been like the canary in the coal mine and there are several commits that have laid claim to "fixing associations".

**Comment by vemv** [comment]
> Just hit this. It would be great to catch this error and report "You may have an invalid assoication in " error instead.

+1. A complete message could be "Association :foo for model Bar is invalid/incomplete. Ensure it's well configured in both parts of the association, including :foreign_key, :class_name and :inverse_of options."
