### ISSUE TITLE
Dashboard NoMethod Error

### ISSUE THREAD

**Issue by ghost** [railsadminteam/rails_admin#1603]
Hello,

Everything was working with Rails Admin, but all of a sudden by Dashboard stopped working and is throwing an error. If I manually type in a url, I can see that the rest of the admin, and all models work correctly, just the dashboard is throwing an error.

Any help would be greatly appreciated.

The error states:

```
NoMethodError in RailsAdmin::MainController#dashboard
undefined method `>' for #<ActiveSupport::OrderedHash:0x007fc0a59f72f8>
```

Here is part of the stack trace:

```
/Users/ac/.rvm/gems/ruby-1.9.3-p392/bundler/gems/rails_admin-b8465f738261/lib/rails_admin/config/actions/dashboard.rb:27:in `block (3 levels) in <class:Dashboard>'
/Users/ac/.rvm/gems/ruby-1.9.3-p392/bundler/gems/rails_admin-b8465f738261/lib/rails_admin/config/actions/dashboard.rb:24:in `each'
/Users/ac/.rvm/gems/ruby-1.9.3-p392/bundler/gems/rails_admin-b8465f738261/lib/rails_admin/config/actions/dashboard.rb:24:in `block (2 levels) in <class:Dashboard>'
(eval):8:in `instance_eval'
(eval):8:in `dashboard'
actionpack (3.2.13) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (3.2.13) lib/abstract_controller/base.rb:167:in `process_action'
actionpack (3.2.13) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (3.2.13) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
activesupport (3.2.13) lib/active_support/callbacks.rb:480:in `_run__1800264818330097842__process_action__1733614161116520272__callbacks'
activesupport (3.2.13) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.13) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
activesupport (3.2.13) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.13) lib/abstract_controller/callbacks.rb:17:in `process_action'
actionpack (3.2.13) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (3.2.13) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
activesupport (3.2.13) lib/active_support/notifications.rb:123:in `block in instrument'
activesupport (3.2.13) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (3.2.13) lib/active_support/notifications.rb:123:in `instrument'
actionpack (3.2.13) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
actionpack (3.2.13) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
activerecord (3.2.13) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (3.2.13) lib/abstract_controller/base.rb:121:in `process'
actionpack (3.2.13) lib/abstract_controller/rendering.rb:45:in `process'
actionpack (3.2.13) lib/action_controller/metal.rb:203:in `dispatch'
```

Here is my gemfile.lock

```
GIT
  remote: git://github.com/sferik/rails_admin.git
  revision: b8465f738261594b8f8864a4bed810ba5c34953f
  specs:
    rails_admin (0.4.7)
      bootstrap-sass (~> 2.2)
      builder (~> 3.0)
      coffee-rails (~> 3.1)
      font-awesome-sass-rails (~> 3.0, >= 3.0.0.1)
      haml (~> 4.0)
      jquery-rails (~> 2.1)
      jquery-ui-rails (~> 3.0)
      kaminari (~> 0.14)
      nested_form (~> 0.3)
      rack-pjax (~> 0.6)
      rails (~> 3.1)
      remotipart (~> 1.0)
      safe_yaml (~> 0.6)
      sass-rails (~> 3.1)

GIT
  remote: git://github.com/timmyc/piggybak_paypal.git
  revision: b892954868c74d6c236466809484d123df7841db
  specs:
    piggybak_paypal (0.0.1)
      rails (~> 3.2.13)

GEM
  remote: https://rubygems.org/
  specs:
    actionmailer (3.2.13)
      actionpack (= 3.2.13)
      mail (~> 2.5.3)
    actionpack (3.2.13)
      activemodel (= 3.2.13)
      activesupport (= 3.2.13)
      builder (~> 3.0.0)
      erubis (~> 2.7.0)
      journey (~> 1.0.4)
      rack (~> 1.4.5)
      rack-cache (~> 1.2)
      rack-test (~> 0.6.1)
      sprockets (~> 2.2.1)
    active_utils (1.0.5)
      activesupport (>= 2.3.11)
      i18n
    activemerchant (1.32.1)
      active_utils (>= 1.0.2)
      activesupport (>= 2.3.14)
      builder (>= 2.0.0)
      i18n
      json (>= 1.5.1)
      money
      nokogiri
    activemodel (3.2.13)
      activesupport (= 3.2.13)
      builder (~> 3.0.0)
    activerecord (3.2.13)
      activemodel (= 3.2.13)
      activesupport (= 3.2.13)
      arel (~> 3.0.2)
      tzinfo (~> 0.3.29)
    activeresource (3.2.13)
      activemodel (= 3.2.13)
      activesupport (= 3.2.13)
    activesupport (3.2.13)
      i18n (= 0.6.1)
      multi_json (~> 1.0)
    acts-as-taggable-on (2.3.3)
      rails (~> 3.0)
    acts_as_list (0.2.0)
      activerecord (>= 3.0)
    ansi (1.4.3)
    arel (3.0.2)
    bcrypt-ruby (3.0.1)
    bootstrap-sass (2.3.1.0)
      sass (~> 3.2)
    builder (3.0.4)
    bullet (4.5.0)
      uniform_notifier
    cancan (1.6.9)
    carrierwave (0.8.0)
      activemodel (>= 3.2.0)
      activesupport (>= 3.2.0)
    coffee-rails (3.2.2)
      coffee-script (>= 2.2.0)
      railties (~> 3.2.0)
    coffee-script (2.2.0)
      coffee-script-source
      execjs
    coffee-script-source (1.6.2)
    countries (0.9.2)
      currencies (>= 0.4.0)
    currencies (0.4.0)
    devise (2.2.3)
      bcrypt-ruby (~> 3.0)
      orm_adapter (~> 0.1)
      railties (~> 3.1)
      warden (~> 1.2.1)
    erubis (2.7.0)
    excon (0.13.4)
    execjs (1.4.0)
      multi_json (~> 1.0)
    figaro (0.6.3)
      bundler (~> 1.0)
      rails (>= 3, < 5)
    fog (1.3.1)
      builder
      excon (~> 0.13.0)
      formatador (~> 0.2.0)
      mime-types
      multi_json (~> 1.0)
      net-scp (~> 1.0.4)
      net-ssh (>= 2.1.3)
      nokogiri (~> 1.5.0)
      ruby-hmac
    font-awesome-sass-rails (3.0.2.2)
      railties (>= 3.1.1)
      sass-rails (>= 3.1.1)
    formatador (0.2.4)
    friendly_id (4.0.9)
    haml (4.0.2)
      tilt
    haml-rails (0.4)
      actionpack (>= 3.1, < 4.1)
      activesupport (>= 3.1, < 4.1)
      haml (>= 3.1, < 4.1)
      railties (>= 3.1, < 4.1)
    hashr (0.0.22)
    hike (1.2.2)
    i18n (0.6.1)
    journey (1.0.4)
    jquery-rails (2.2.1)
      railties (>= 3.0, < 5.0)
      thor (>= 0.14, < 2.0)
    jquery-ui-rails (3.0.1)
      jquery-rails
      railties (>= 3.1.0)
    json (1.7.7)
    kaminari (0.14.1)
      actionpack (>= 3.0.0)
      activesupport (>= 3.0.0)
    kgio (2.8.0)
    mail (2.5.3)
      i18n (>= 0.4.0)
      mime-types (~> 1.16)
      treetop (~> 1.4.8)
    meta-tags (1.4.1)
      actionpack
    meta_request (0.2.3)
      rack-contrib
      railties
    mime-types (1.22)
    mini_magick (3.5.0)
      subexec (~> 0.2.1)
    money (5.1.1)
      i18n (~> 0.6.0)
    multi_json (1.7.2)
    nested_form (0.3.2)
    net-scp (1.0.4)
      net-ssh (>= 1.99.1)
    net-ssh (2.6.7)
    nokogiri (1.5.9)
    orm_adapter (0.4.0)
    pg (0.15.1)
    piggybak (0.6.28)
      activemerchant
      countries
      devise
      rack-ssl-enforcer
      rails (~> 3.2.8)
      rails_admin (~> 0.4.5)
    piggybak_variants (0.0.15)
      rails (~> 3.2.3)
    polyglot (0.3.3)
    rack (1.4.5)
    rack-cache (1.2)
      rack (>= 0.4)
    rack-contrib (1.1.0)
      rack (>= 0.9.1)
    rack-pjax (0.7.0)
      nokogiri (~> 1.5)
      rack (~> 1.3)
    rack-ssl (1.3.3)
      rack
    rack-ssl-enforcer (0.2.5)
    rack-test (0.6.2)
      rack (>= 1.0)
    rails (3.2.13)
      actionmailer (= 3.2.13)
      actionpack (= 3.2.13)
      activerecord (= 3.2.13)
      activeresource (= 3.2.13)
      activesupport (= 3.2.13)
      bundler (~> 1.0)
      railties (= 3.2.13)
    railties (3.2.13)
      actionpack (= 3.2.13)
      activesupport (= 3.2.13)
      rack-ssl (~> 1.3.2)
      rake (>= 0.8.7)
      rdoc (~> 3.4)
      thor (>= 0.14.6, < 2.0)
    raindrops (0.10.0)
    rake (10.0.4)
    rdoc (3.12.2)
      json (~> 1.4)
    redactor-rails (0.3.3)
      devise
      mime-types
      orm_adapter
    remotipart (1.0.5)
    rest-client (1.6.7)
      mime-types (>= 1.16)
    rmagick (2.13.2)
    ruby-hmac (0.4.0)
    safe_yaml (0.9.0)
    sass (3.2.7)
    sass-rails (3.2.6)
      railties (~> 3.2.0)
      sass (>= 3.1.10)
      tilt (~> 1.3)
    sprockets (2.2.2)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    subexec (0.2.3)
    thor (0.18.1)
    tilt (1.3.7)
    tire (0.5.7)
      activemodel (>= 3.0)
      activesupport
      ansi
      hashr (~> 0.0.19)
      multi_json (~> 1.3)
      rake
      rest-client (~> 1.6)
    treetop (1.4.12)
      polyglot
      polyglot (>= 0.3.1)
    turbolinks (1.1.1)
      coffee-rails
    tzinfo (0.3.37)
    uglifier (2.0.1)
      execjs (>= 0.3.0)
      multi_json (~> 1.0, >= 1.0.2)
    unicorn (4.6.2)
      kgio (~> 2.6)
      rack
      raindrops (~> 0.7)
    unicorn-rails (1.0.1)
      rack
      unicorn
    uniform_notifier (1.2.0)
    warden (1.2.1)
      rack (>= 1.0)

PLATFORMS
  ruby

DEPENDENCIES
  acts-as-taggable-on (>= 2.3.1)
  acts_as_list
  bullet
  cancan
  carrierwave
  coffee-rails (~> 3.2.1)
  countries
  devise
  figaro
  fog (~> 1.3.1)
  friendly_id (~> 4.0.9)
  haml-rails
  jquery-rails
  kaminari
  meta-tags
  meta_request
  mini_magick
  pg
  piggybak (= 0.6.28)
  piggybak_paypal!
  piggybak_variants (= 0.0.15)
  rails (= 3.2.13)
  rails_admin!
  redactor-rails
  rmagick (= 2.13.2)
  sass-rails (~> 3.2.3)
  tire (= 0.5.7)
  turbolinks
  uglifier (>= 1.0.3)
  unicorn-rails
```

**Comment by phil4lif** [comment]
I am suddenly getting this error as well.
