### ISSUE TITLE
crash on querying models with json columns

### ISSUE THREAD

**Issue by wlipa** [railsadminteam/rails_admin#2502]
If you search / query a model with a jsonb field, and your search query is plain text (like "aa"), then the server will throw a JSON parser exception like the following:

```
 JSON::ParserError (757: unexpected token at '11'):
   json (1.8.3) lib/json/common.rb:155:in `parse'
   json (1.8.3) lib/json/common.rb:155:in `parse'
   rails_admin (0.8.1) lib/rails_admin/config/fields/types/json.rb:17:in `parse_value'
   rails_admin (0.8.1) lib/rails_admin/adapters/active_record.rb:121:in `block in query_scope'
   rails_admin (0.8.1) lib/rails_admin/adapters/active_record.rb:120:in `each'
   rails_admin (0.8.1) lib/rails_admin/adapters/active_record.rb:120:in `query_scope'
   rails_admin (0.8.1) lib/rails_admin/adapters/active_record.rb:33:in `all'
   rails_admin (0.8.1) app/controllers/rails_admin/main_controller.rb:131:in `get_collection'
   rails_admin (0.8.1) app/controllers/rails_admin/main_controller.rb:37:in `list_entries'
   rails_admin (0.8.1) lib/rails_admin/config/actions/index.rb:30:in `block (2 levels) in <class:Index>'
   rails_admin (0.8.1) app/controllers/rails_admin/main_controller.rb:22:in `instance_eval'
```

A workaround is to configure the json field as non-queryable.

**Comment by kevinryantao** [comment]
I also reproduced this exact error.

**Comment by kevinryantao** [comment]
I believe this bug was introduced from this commit: https://github.com/sferik/rails_admin/commit/fe2899fdeb48f4cdf33c0616f0024df13fd32f14

The problem is that it tries to run JSON.parse(value) even when it's not valid JSON.

**Comment by zegomesjf** [comment]
:+1: for @kevinryantao solution

**Comment by bbenezech** [comment]
I guess JSONB should be non-queryable. Can someone provide a PR?

**Comment by krainboltgreene** [comment]
It's not that it should be non-queryable, but rather it should be coerced into text.

**Comment by jtoy** [comment]
is this fixed? this seems like something a lot of people would run into

**Comment by Saicheg** [comment]
👍 for this issue

**Comment by mapreal19** [comment]
Until this is fixed you could use this workaround in your configuration:

```ruby
ActiveRecord::Base.descendants.each do |model|
  config.model "#{model.name}" do
    exclude_fields_if { type == :json }
  end
end
```

**Comment by jtoy** [comment]
That seems to exclude it always. Anyway to just exclude that in searches?

-- Sent from my mobile

**Comment by mapreal19** [comment]
@jtoy Yes. This would exclude it for all the models that have json columns

**Comment by jtoy** [comment]
@mapreal19 i couldn't get this working, are you using this?

**Comment by mapreal19** [comment]
@jtoy I ended up making those json attrs non-queryable. Give this a try:

```ruby
 ActiveRecord::Base.descendants.each do |model|
    config.model(model.name.to_s) do
      fields_of_type(:json) { queryable false }
    end
  end
```

**Comment by jtoy** [comment]
this works, thank you!

**Comment by fny** [comment]
Note for Rails 5 (or any situation where you have an abstract model defined like ApplicationRecord), you'll need to skip abstract classes:

```ruby
  ActiveRecord::Base.descendants.each do |model|
    next if model.abstract_class?
    config.model(model.name.to_s) do
      fields_of_type(:json) { queryable false }
    end
  end
```

**Comment by MatthiasRMS** [comment]
@jtoy thanks for the workaround, should this go in an initializer or in dev/prod/test.rb? I've tried to add it to a rails_admin.rb initializer and to development.rb file but none worked.

**Comment by serg-kovalev** [comment]
@MatthiasRMS Did you eager load your models beforehand as @fny suggested?

```ruby
Rails.application.eager_load!
ActiveRecord::Base.descendants.each do |model|
  next if model.abstract_class? # comment out this line if you are on Rails < 5
  config.model(model.name.to_s) do
    fields_of_type(:json) { queryable false }
  end
end
```

**Comment by sbull** [comment]
Here is my workaround, in an initializer:
```ruby
RailsAdmin::Config::Fields::Types::Json.inspect # Load before override.
class RailsAdmin::Config::Fields::Types::Json
  def queryable?
    false
  end
end
```

**Comment by MatthiasRMS** [comment]
None of the above worked for me.
This fixed it:

```
RailsAdmin.config do |config|
  ApplicationRecord.descendants.each do |model|
    next if model.abstract_class?
    config.model(model.name.to_s) do
      exclude_fields_if do
        type == :json
      end

      exclude_fields_if do
        type == :jsonb
      end
    end
  end
end
```

**Comment by drewbaumann** [comment]
@MatthiasRMS solution worked for us with small tweaks:

```
Rails.application.eager_load!
  ActiveRecord::Base.descendants.each do |model|
    next if model.abstract_class?
    config.model(model.name.to_s) do
      exclude_fields_if do
        [:json, :jsonb].include?(type)
      end
    end
  end
```

**Comment by jeromedalbert** [comment]
I didn't want to use the descendants technique, I don't want to enable eager loading just because of a bug in rails_admin.

So I used @sbull's solution with the following tweak to make it work with the current rails_admin version at the time of writing (1.4.2):

```ruby
# Prevent json fields from being queried, since RailsAdmin cannot handle them
RailsAdmin::Config::Fields::Types::Json.inspect
class RailsAdmin::Config::Fields::Types::Json
  register_instance_option :queryable? do
    false
  end
end
```

**Comment by jeromedalbert** [comment]
Alternatively the following code works too, and does not make RailsAdmin crash with a 500 error if you enter bad JSON data:

```ruby
# Don't blow up RailsAdmin on JSON searches or invalid JSON formats
module RailsAdmin
  module Config
    module Fields
      module Types
        class Json
          register_instance_option :formatted_value do
            if value.is_a?(Hash) || value.is_a?(Array)
              JSON.pretty_generate(value)
            else
              value
            end
          end

          def parse_value(value)
            value.present? ? JSON.parse(value) : nil
          rescue JSON::ParserError
            value
          end
        end
      end
    end
  end
end
```

**Comment by mltsy** [comment]
This seems to prevent an error, but even when I put in a valid JSON value to query by, the query by doesn't actually search the JSON field (it just returns no records), or if I filter specifically by the JSON field (an array in my case), it returns all records, regardless of a match.

**Comment by AhmadIbrahiim** [comment]
This above solution seems to prevent rails_admin from render any JSON, Any recommendation on how to return it as plain text?

**Comment by jacobjlevine** [comment]
I think I found a way of hacking the search function to work with JSONB fields. It casts the entire JSONB field as text, which means your search will also include key names.
```
list do
  field :field_name, :string do
    queryable true
    searchable_columns [{ column: "field_name::TEXT", type: :string }]
  end
end
```
Hope this helps! Maybe someone else can figure out how to eliminate the key names? And maybe this could also serve as the foundation for a more general solution that can be integrated into the core project?

**Comment by mshibuya** [comment]
This turned out to already be fixed, though not by a change targeting this specifically. A more recent fix (for #3754, malformed hand-written filter URLs) made value-parsing for search/filter conditions defensive in general: if a field can't make sense of the term it's given (invalid JSON, an out-of-range date, etc.), that field is now simply excluded from the condition instead of raising and taking the whole page down. A `JSON::ParserError` from a plain-text query against a json/jsonb column falls under that same guard now.

Closing as fixed.
