### ISSUE TITLE
NoMethodError: undefined method `parse_value' for nil:NilClass when using custom filter parameters

### ISSUE THREAD

**Issue by leegeng** [railsadminteam/rails_admin#2756]
Ruby: 2.3.1
Rails: 4.2.7
OS: MacOS Sierra 10.12.1
Gem: 1.0.0

I'm trying to make a custom filter on a model's list. 
In this case, I put some parameters on ```f``` hash. (some of them are defined as a field in config, and the others are not because their origin database is different. I wanted to remake query on index_extension.)

I got an error like this because field parameter is nil. (https://github.com/sferik/rails_admin/blob/master/lib/rails_admin/adapters/active_record.rb#L140)

```
NoMethodError: undefined method `parse_value' for nil:NilClass
  from rails_admin/abstract_model.rb:114:in `parse_field_value'
  from rails_admin/adapters/active_record.rb:140:in `block (2 levels) in filter_scope'
  from action_controller/metal/strong_parameters.rb:185:in `each_pair'
  from action_controller/metal/strong_parameters.rb:185:in `each_pair'
  from rails_admin/adapters/active_record.rb:137:in `block in filter_scope'
  from action_controller/metal/strong_parameters.rb:185:in `each_pair'
  from action_controller/metal/strong_parameters.rb:185:in `each_pair'
  from rails_admin/adapters/active_record.rb:136:in `filter_scope'
  from rails_admin/adapters/active_record.rb:34:in `all'
  from rails_admin/main_controller.rb:131:in `get_collection'
  from rails_admin/main_controller.rb:37:in `list_entries'
  from lib/rails_admin/config/actions/index_extension.rb:12:in `block in controller'
  from rails_admin/main_controller.rb:22:in `instance_eval'
  from rails_admin/main_controller.rb:22:in `index'
  from action_controller/metal/implicit_render.rb:4:in `send_action'
  from abstract_controller/base.rb:198:in `process_action'
  from action_controller/metal/rendering.rb:10:in `process_action'
  from abstract_controller/callbacks.rb:20:in `block in process_action'
  from active_support/callbacks.rb:117:in `call'
  from active_support/callbacks.rb:555:in `block (2 levels) in compile'
  from active_support/callbacks.rb:505:in `call'
  from active_support/callbacks.rb:92:in `__run_callbacks__'
  from active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  from active_support/callbacks.rb:81:in `run_callbacks'
  from abstract_controller/callbacks.rb:19:in `process_action'
  from action_controller/metal/rescue.rb:29:in `process_action'
  from action_controller/metal/instrumentation.rb:32:in `block in process_action'
  from active_support/notifications.rb:164:in `block in instrument'
  from active_support/notifications/instrumenter.rb:20:in `instrument'
  from active_support/notifications.rb:164:in `instrument'
  from action_controller/metal/instrumentation.rb:30:in `process_action'
  from action_controller/metal/params_wrapper.rb:250:in `process_action'
  from active_record/railties/controller_runtime.rb:18:in `process_action'
  from abstract_controller/base.rb:137:in `process'
  from action_view/rendering.rb:30:in `process'
  from action_controller/metal.rb:196:in `dispatch'
  from action_controller/metal/rack_delegation.rb:13:in `dispatch'
  from action_controller/metal.rb:237:in `block in action'
  from action_dispatch/routing/route_set.rb:74:in `dispatch'
  from action_dispatch/routing/route_set.rb:43:in `serve'
  from action_dispatch/journey/router.rb:43:in `block in serve'
  from action_dispatch/journey/router.rb:30:in `each'
  from action_dispatch/journey/router.rb:30:in `serve'
  from action_dispatch/routing/route_set.rb:817:in `call'
  from rails/engine.rb:518:in `call'
  from rails/railtie.rb:194:in `public_send'
  from rails/railtie.rb:194:in `method_missing'
  from action_dispatch/routing/mapper.rb:51:in `serve'
  from action_dispatch/journey/router.rb:43:in `block in serve'
  from action_dispatch/journey/router.rb:30:in `each'
  from action_dispatch/journey/router.rb:30:in `serve'
  from action_dispatch/routing/route_set.rb:817:in `call'
  from rack/pjax.rb:12:in `call'
  from action_dispatch/middleware/flash.rb:260:in `call'
  from active_elastic_job/rack/sqs_message_consumer.rb:51:in `call'
  from warden/manager.rb:35:in `block in call'
  from warden/manager.rb:34:in `catch'
  from warden/manager.rb:34:in `call'
  from rack/etag.rb:24:in `call'
  from rack/conditionalget.rb:25:in `call'
  from rack/head.rb:13:in `call'
  from remotipart/middleware.rb:32:in `call'
  from action_dispatch/middleware/params_parser.rb:27:in `call'
  from action_dispatch/middleware/flash.rb:260:in `call'
  from rack/session/abstract/id.rb:225:in `context'
  from rack/session/abstract/id.rb:220:in `call'
  from action_dispatch/middleware/cookies.rb:560:in `call'
  from active_record/query_cache.rb:36:in `call'
  from active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  from active_record/migration.rb:377:in `call'
  from action_dispatch/middleware/callbacks.rb:29:in `block in call'
  from active_support/callbacks.rb:88:in `__run_callbacks__'
  from active_support/callbacks.rb:778:in `_run_call_callbacks'
  from active_support/callbacks.rb:81:in `run_callbacks'
  from action_dispatch/middleware/callbacks.rb:27:in `call'
  from action_dispatch/middleware/reloader.rb:73:in `call'
  from action_dispatch/middleware/remote_ip.rb:78:in `call'
  from action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  from web_console/middleware.rb:28:in `block in call'
  from web_console/middleware.rb:18:in `catch'
  from web_console/middleware.rb:18:in `call'
  from action_dispatch/middleware/show_exceptions.rb:30:in `call'
  from rails/rack/logger.rb:38:in `call_app'
  from rails/rack/logger.rb:20:in `block in call'
  from active_support/tagged_logging.rb:68:in `block in tagged'
  from active_support/tagged_logging.rb:26:in `tagged'
  from active_support/tagged_logging.rb:68:in `tagged'
  from rails/rack/logger.rb:20:in `call'
  from action_dispatch/middleware/request_id.rb:21:in `call'
  from rack/methodoverride.rb:22:in `call'
  from rack/runtime.rb:18:in `call'
  from active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  from rack/lock.rb:17:in `call'
  from action_dispatch/middleware/static.rb:120:in `call'
  from rack/sendfile.rb:113:in `call'
  from raven/integrations/rack.rb:50:in `call'
  from rails/engine.rb:518:in `call'
  from rails/application.rb:165:in `call'
  from rack/content_length.rb:15:in `call'
  from puma/configuration.rb:225:in `call'
  from puma/server.rb:578:in `handle_request'
  from puma/server.rb:415:in `process_client'
  from puma/server.rb:275:in `block in run'
  from puma/thread_pool.rb:116:in `block in spawn_thread'
```

I think it should check whether the value is nil or not, and I solved this problem by adding a line of code ```next if field.nil?```

**Comment by mshibuya** [comment]
Considering this to be stale.
