### ISSUE TITLE
No route matches {:action=>"show", :controller=>"rails_admin/main", :id=>nil, :model_name=>"asker"}

### ISSUE THREAD

**Issue by alagu** [railsadminteam/rails_admin#2853]
Hey @sferik and team,

I'm getting this error when I try to open the edit page of asker. Here is the complete error:

```
ActionController::UrlGenerationError - No route matches {:action=>"show", :controller=>"rails_admin/main", :id=>nil, :model_name=>"asker"}:
  actionpack (4.2.5.2) lib/action_dispatch/journey/formatter.rb:46:in `generate'
  actionpack (4.2.5.2) lib/action_dispatch/routing/route_set.rb:719:in `generate'
  actionpack (4.2.5.2) lib/action_dispatch/routing/route_set.rb:750:in `generate'
  actionpack (4.2.5.2) lib/action_dispatch/routing/route_set.rb:797:in `url_for'
  actionpack (4.2.5.2) lib/action_dispatch/routing/url_for.rb:156:in `url_for'
  actionview (4.2.5.2) lib/action_view/routing_url_for.rb:94:in `url_for'
  rails_admin (1.1.1) lib/rails_admin/config/fields/association.rb:24:in `block (2 levels) in <class:Association>'
  rails_admin (1.1.1) lib/rails_admin/config/fields/association.rb:19:in `block in <class:Association>'
  rails_admin (1.1.1) lib/rails_admin/config/configurable.rb:66:in `block in register_instance_option'
  rails_admin (1.1.1) lib/rails_admin/config/proxyable/proxy.rb:27:in `method_missing'
  rails_admin (1.1.1) app/helpers/rails_admin/form_builder.rb:73:in `field_for'
  rails_admin (1.1.1) app/helpers/rails_admin/form_builder.rb:58:in `block in input_for'
  actionview (4.2.5.2) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
  actionview (4.2.5.2) lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'
  haml (4.0.7) lib/haml/helpers/action_view_xss_mods.rb:5:in `with_output_buffer_with_haml_xss'
  actionview (4.2.5.2) lib/action_view/helpers/capture_helper.rb:38:in `capture'
  haml (4.0.7) lib/haml/helpers/action_view_mods.rb:52:in `capture_with_haml'
  actionview (4.2.5.2) lib/action_view/helpers/tag_helper.rb:106:in `content_tag'
  haml (4.0.7) lib/haml/helpers/action_view_mods.rb:69:in `content_tag_with_haml'
  rails_admin (1.1.1) app/helpers/rails_admin/form_builder.rb:57:in `input_for'
  rails_admin (1.1.1) app/helpers/rails_admin/form_builder.rb:46:in `block in field_wrapper_for'
  actionview (4.2.5.2) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
  actionview (4.2.5.2) lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'
  haml (4.0.7) lib/haml/helpers/action_view_xss_mods.rb:5:in `with_output_buffer_with_haml_xss'
  actionview (4.2.5.2) lib/action_view/helpers/capture_helper.rb:38:in `capture'
  haml (4.0.7) lib/haml/helpers/action_view_mods.rb:52:in `capture_with_haml'
  actionview (4.2.5.2) lib/action_view/helpers/tag_helper.rb:106:in `content_tag'
  haml (4.0.7) lib/haml/helpers/action_view_mods.rb:69:in `content_tag_with_haml'
  rails_admin (1.1.1) app/helpers/rails_admin/form_builder.rb:44:in `field_wrapper_for'
  rails_admin (1.1.1) app/helpers/rails_admin/form_builder.rb:35:in `block (2 levels) in fieldset_for'
  rails_admin (1.1.1) app/helpers/rails_admin/form_builder.rb:35:in `block in fieldset_for'
  actionview (4.2.5.2) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
  actionview (4.2.5.2) lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'
  haml (4.0.7) lib/haml/helpers/action_view_xss_mods.rb:5:in `with_output_buffer_with_haml_xss'
  actionview (4.2.5.2) lib/action_view/helpers/capture_helper.rb:38:in `capture'
  haml (4.0.7) lib/haml/helpers/action_view_mods.rb:52:in `capture_with_haml'
  actionview (4.2.5.2) lib/action_view/helpers/tag_helper.rb:106:in `content_tag'
  haml (4.0.7) lib/haml/helpers/action_view_mods.rb:69:in `content_tag_with_haml'
  rails_admin (1.1.1) app/helpers/rails_admin/form_builder.rb:31:in `fieldset_for'
  rails_admin (1.1.1) app/helpers/rails_admin/form_builder.rb:16:in `block (2 levels) in generate'
  rails_admin (1.1.1) app/helpers/rails_admin/form_builder.rb:15:in `block in generate'
  rails_admin (1.1.1) app/helpers/rails_admin/form_builder.rb:131:in `without_field_error_proc_added_div'
  rails_admin (1.1.1) app/helpers/rails_admin/form_builder.rb:7:in `generate'
  rails_admin (1.1.1) app/views/rails_admin/main/_form_nested_one.html.haml:17:in `block in ___sers_alagu__rbenv_versions_______lib_ruby_gems_______gems_rails_admin_______app_views_rails_admin_main__form_nested_one_html_haml__1588045689576725308_70210875591800'
  haml (4.0.7) lib/haml/helpers.rb:368:in `block in capture_haml'
  haml (4.0.7) lib/haml/helpers.rb:608:in `with_haml_buffer'
  haml (4.0.7) lib/haml/helpers.rb:364:in `capture_haml'
  haml (4.0.7) lib/haml/helpers/xss_mods.rb:61:in `capture_haml_with_haml_xss'
  haml (4.0.7) lib/haml/helpers/action_view_mods.rb:45:in `capture_with_haml'
  actionview (4.2.5.2) lib/action_view/helpers/form_helper.rb:1925:in `block in fields_for_nested_model'
  actionview (4.2.5.2) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
  actionview (4.2.5.2) lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'
  haml (4.0.7) lib/haml/helpers/action_view_xss_mods.rb:5:in `with_output_buffer_with_haml_xss'
  actionview (4.2.5.2) lib/action_view/helpers/capture_helper.rb:38:in `capture'
  haml (4.0.7) lib/haml/helpers/action_view_mods.rb:52:in `capture_with_haml'
  actionview (4.2.5.2) lib/action_view/helpers/form_helper.rb:714:in `fields_for'
  actionview (4.2.5.2) lib/action_view/helpers/form_helper.rb:1924:in `fields_for_nested_model'
  nested_form (0.3.2) lib/nested_form/builder_mixin.rb:98:in `fields_for_nested_model'
  actionview (4.2.5.2) lib/action_view/helpers/form_helper.rb:1914:in `fields_for_with_nested_attributes'
  nested_form (0.3.2) lib/nested_form/builder_mixin.rb:87:in `fields_for_with_nested_attributes'
  actionview (4.2.5.2) lib/action_view/helpers/form_helper.rb:1582:in `fields_for'
  nested_form (0.3.2) lib/nested_form/builder_mixin.rb:43:in `block in link_to_add'
  nested_form (0.3.2) lib/nested_form/view_helper.rb:53:in `after_nested_form_callbacks'
  rails_admin (1.1.1) app/helpers/rails_admin/main_helper.rb:9:in `rails_admin_form_for'
  rails_admin (1.1.1) app/views/rails_admin/main/edit.html.haml:1:in `___sers_alagu__rbenv_versions_______lib_ruby_gems_______gems_rails_admin_______app_views_rails_admin_main_edit_html_haml___1145832162973261280_70210888089380'
  actionview (4.2.5.2) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.5.2) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.5.2) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.5.2) lib/action_view/template.rb:143:in `render'
  actionview (4.2.5.2) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
  actionview (4.2.5.2) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
  activesupport (4.2.5.2) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.5.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.5.2) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.5.2) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
  actionview (4.2.5.2) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
  actionview (4.2.5.2) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
  actionview (4.2.5.2) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
  actionview (4.2.5.2) lib/action_view/renderer/template_renderer.rb:14:in `render'
  actionview (4.2.5.2) lib/action_view/renderer/renderer.rb:46:in `render_template'
  actionview (4.2.5.2) lib/action_view/renderer/renderer.rb:27:in `render'
  actionview (4.2.5.2) lib/action_view/rendering.rb:100:in `_render_template'
  actionpack (4.2.5.2) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.2.5.2) lib/action_view/rendering.rb:83:in `render_to_body'
  actionpack (4.2.5.2) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.2.5.2) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
  actionpack (4.2.5.2) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.2.5.2) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.2.5.2) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  activesupport (4.2.5.2) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /Users/alagu/.rbenv/versions/2.1.5/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
  activesupport (4.2.5.2) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.2.5.2) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  actionpack (4.2.5.2) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  activerecord (4.2.5.2) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.2.5.2) lib/action_controller/metal/instrumentation.rb:43:in `render'
  remotipart (1.3.1) lib/remotipart/render_overrides.rb:16:in `render_with_remotipart'
  rails_admin (1.1.1) lib/rails_admin/config/actions/edit.rb:20:in `block (4 levels) in <class:Edit>'
  actionpack (4.2.5.2) lib/action_controller/metal/mime_responds.rb:217:in `respond_to'
  rails_admin (1.1.1) lib/rails_admin/config/actions/edit.rb:19:in `block (2 levels) in <class:Edit>'
  rails_admin (1.1.1) app/controllers/rails_admin/main_controller.rb:22:in `edit'
  actionpack (4.2.5.2) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.5.2) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.5.2) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.5.2) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.5.2) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.5.2) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.5.2) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.5.2) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.5.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.5.2) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.5.2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.5.2) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.5.2) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.5.2) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.5.2) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.5.2) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.5.2) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.5.2) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.5.2) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.5.2) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.5.2) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.5.2) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.5.2) lib/action_dispatch/routing/route_set.rb:815:in `call'
  railties (4.2.5.2) lib/rails/engine.rb:518:in `call'
  railties (4.2.5.2) lib/rails/railtie.rb:194:in `method_missing'
  actionpack (4.2.5.2) lib/action_dispatch/routing/mapper.rb:51:in `serve'
  actionpack (4.2.5.2) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.5.2) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.5.2) lib/action_dispatch/routing/route_set.rb:815:in `call'
  rack-pjax (1.0.0) lib/rack/pjax.rb:12:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/flash.rb:260:in `call'
  simple_captcha2 (0.4.3) lib/simple_captcha/middleware.rb:47:in `call'
  warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
  warden (1.2.7) lib/warden/manager.rb:35:in `call'
  rack (1.6.5) lib/rack/etag.rb:24:in `call'
  rack (1.6.5) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.5) lib/rack/head.rb:13:in `call'
  remotipart (1.3.1) lib/remotipart/middleware.rb:32:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.5) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.5) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.5.2) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.5.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  activerecord (4.2.5.2) lib/active_record/migration.rb:377:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.3.0) lib/web_console/middleware.rb:28:in `block in call'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.5.2) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.5.2) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.5.2) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.5.2) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.5.2) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.5.2) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.5) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.5) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.5.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.5) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.5) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.5.2) lib/rails/engine.rb:518:in `call'
  railties (4.2.5.2) lib/rails/application.rb:165:in `call'
  rack (1.6.5) lib/rack/tempfile_reaper.rb:15:in `call'
  rack (1.6.5) lib/rack/lint.rb:49:in `_call'
  rack (1.6.5) lib/rack/lint.rb:37:in `call'
  rack (1.6.5) lib/rack/showexceptions.rb:24:in `call'
  rack (1.6.5) lib/rack/commonlogger.rb:33:in `call'
  rack (1.6.5) lib/rack/chunked.rb:54:in `call'
  rack (1.6.5) lib/rack/content_length.rb:15:in `call'
  rack (1.6.5) lib/rack/handler/webrick.rb:88:in `service'
  /Users/alagu/.rbenv/versions/2.1.5/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
  /Users/alagu/.rbenv/versions/2.1.5/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
  /Users/alagu/.rbenv/versions/2.1.5/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'

```

Here is the skeleton of complete setup:

https://gist.github.com/alagu/60e876fa33cbf830b816d878b9afa71c

I've tried adding an asker.rb (though I don't use it)

```
class AskersController < ApplicationController
  def show
    render :text => 'OK'
  end

  def edit
    
  end
end
```

Still, it doesn't work. Any help is appreciated.

**Comment by BrunoQuaresma** [comment]
Any update?

**Comment by mshibuya** [comment]
Most possible cause will be that you have show action disabled.
https://github.com/railsadminteam/rails_admin/wiki/Actions#default
