### ISSUE TITLE
Error when trying to upgrade rails admin from 2.0.2 to 3.0.0.beta

### ISSUE THREAD

**Issue by estebanz01** [railsadminteam/rails_admin#3452]
**Describe the bug**
Hello! 👋 

I'm getting an error when trying to run the generator to migrate to `rails_admin` 3.0.0.beta with rails 6.0.4.4 and ruby 2.7.4.

```ruby
          ?  Where do you want to mount rails_admin? Press <enter> for [admin] > admin
       route  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
      insert  config/initializers/rails_admin.rb
           -  Using [webpacker] for asset delivery method
Traceback (most recent call last):
        19: from bin/rails:4:in `<main>'
        18: from bin/rails:4:in `require'
        17: from /home/ubuntu/.rvm/gems/ruby-2.7.4@ark/gems/railties-6.0.4.4/lib/rails/commands.rb:18:in `<top (required)>'
        16: from /home/ubuntu/.rvm/gems/ruby-2.7.4@ark/gems/railties-6.0.4.4/lib/rails/command.rb:46:in `invoke'
        15: from /home/ubuntu/.rvm/gems/ruby-2.7.4@ark/gems/railties-6.0.4.4/lib/rails/command/base.rb:69:in `perform'
        14: from /home/ubuntu/.rvm/gems/ruby-2.7.4@ark/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
        13: from /home/ubuntu/.rvm/gems/ruby-2.7.4@ark/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
        12: from /home/ubuntu/.rvm/gems/ruby-2.7.4@ark/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
        11: from /home/ubuntu/.rvm/gems/ruby-2.7.4@ark/gems/railties-6.0.4.4/lib/rails/commands/generate/generate_command.rb:26:in `perform'
        10: from /home/ubuntu/.rvm/gems/ruby-2.7.4@ark/gems/railties-6.0.4.4/lib/rails/generators.rb:276:in `invoke'
         9: from /home/ubuntu/.rvm/gems/ruby-2.7.4@ark/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
         8: from /home/ubuntu/.rvm/gems/ruby-2.7.4@ark/gems/thor-1.1.0/lib/thor/group.rb:232:in `dispatch'
         7: from /home/ubuntu/.rvm/gems/ruby-2.7.4@ark/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `invoke_all'
         6: from /home/ubuntu/.rvm/gems/ruby-2.7.4@ark/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `map'
         5: from /home/ubuntu/.rvm/gems/ruby-2.7.4@ark/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `each'
         4: from /home/ubuntu/.rvm/gems/ruby-2.7.4@ark/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `block in invoke_all'
         3: from /home/ubuntu/.rvm/gems/ruby-2.7.4@ark/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
         2: from /home/ubuntu/.rvm/gems/ruby-2.7.4@ark/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
         1: from /home/ubuntu/.rvm/gems/ruby-2.7.4@ark/gems/rails_admin-3.0.0.beta/lib/generators/rails_admin/install_generator.rb:26:in `install'
/home/ubuntu/.rvm/gems/ruby-2.7.4@ark/gems/rails_admin-3.0.0.beta/lib/generators/rails_admin/install_generator.rb:51:in `configure_for_webpacker5': uninitialized constant RailsAdmin::Version (NameError)
```

**Reproduction steps**
- Have `rails_admin` installed in version 2.0.2 ( `gem 'rails_admin', '~> 2.0.2'` in Gemfile).
- Change `rails_admin` to version `3.0.0.beta`.
- Run `bundle update rails_admin`.
- Run `bundle exec rails g rails_admin:install`

**Expected behavior**
I expect to have a `rails_admin.rb` initializer with the updated values for 3.0.0.beta.

**Additional context**

- `rails` version: 6.0.4.4
- `rails_admin` version: 3.0.0.beta
- full stack trace (if there's an exception)

**Comment by estebanz01** [comment]
After manually editing `lib/generators/rails_admin/install_generator.rb` yo not use the `rails_admin` version constant, yarn ask me to select `3.0.0.beta` or `3.0.0.alpha` so I'm not sure if the gem really needs to depend on that.

**Comment by mshibuya** [comment]
Thanks for reporting, just pushed the fix. Could you try with the master branch?

```ruby
gem 'rails_admin', github: 'railsadminteam/rails_admin'
```

**Comment by estebanz01** [comment]
working as expected 😀
