### ISSUE TITLE
Error: Incompatible units: 'rem' and 'px'.

### ISSUE THREAD

**Issue by seb-sykio** [railsadminteam/rails_admin#3473]
hi

hi
after updating from 3.0.0.beta2 to 3.0.0.rc I have this error:
```

Failure/Error: $nav-link-height:                   $font-size-base * $line-height-base + $nav-link-padding-y * 2 !default;

ActionView::Template::Error:
Error: Incompatible units: 'rem' and 'px'.
on line 1116:37 of ../../../../.rvm/gems/ruby-3.1.0/bundler/gems/rails_admin-ac0a563a0bf9/vendor/assets/stylesheets/rails_admin/bootstrap/_variables.scss
from line 11:9 of ../../../../.rvm/gems/ruby-3.1.0/bundler/gems/rails_admin-ac0a563a0bf9/vendor/assets/stylesheets/rails_admin/bootstrap/bootstrap.scss
from line 15:9 of ../../../../.rvm/gems/ruby-3.1.0/bundler/gems/rails_admin-ac0a563a0bf9/app/assets/stylesheets/rails_admin/application.scss
>> $nav-link-height:                   $font-size-base * $line-height-base + $n
------------------------------------^
# .rvm/gems/ruby-3.1.0/gems/sassc-2.4.0/lib/sassc/engine.rb:50:in `render'
# .rvm/gems/ruby-3.1.0/gems/sassc-rails-2.1.2/lib/sassc/rails/template.rb:40:in `block in call'
# .rvm/gems/ruby-3.1.0/gems/sprockets-4.0.2/lib/sprockets/utils.rb:138:in `module_include'
# .rvm/gems/ruby-3.1.0/gems/sassc-rails-2.1.2/lib/sassc/rails/template.rb:39:in `call'
# .rvm/gems/ruby-3.1.0/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:84:in `call_processor'
# .rvm/gems/ruby-3.1.0/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
# .rvm/gems/ruby-3.1.0/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:65:in `reverse_each'
# .rvm/gems/ruby-3.1.0/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:65:in `call_processors'
# .rvm/gems/ruby-3.1.0/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:22:in `block in <class:CompositeProcessor>'
# .rvm/gems/ruby-3.1.0/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:33:in `call'
# .rvm/gems/ruby-3.1.0/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:84:in `call_processor'
# .rvm/gems/ruby-3.1.0/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
# .rvm/gems/ruby-3.1.0/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:65:in `reverse_each'
# .rvm/gems/ruby-3.1.0/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:65:in `call_processors'
# .rvm/gems/ruby-3.1.0/gems/sprockets-4.0.2/lib/sprockets/loader.rb:182:in `load_from_unloaded'
# .rvm/gems/ruby-3.1.0/gems/sprockets-4.0.2/lib/sprockets/loader.rb:59:in `block in load'
# .rvm/gems/ruby-3.1.0/gems/sprockets-4.0.2/lib/sprockets/loader.rb:337:in `fetch_asset_from_dependency_cache'
# .rvm/gems/ruby-3.1.0/gems/sprockets-4.0.2/lib/sprockets/loader.rb:43:in `load'
# .rvm/gems/ruby-3.1.0/gems/sprockets-4.0.2/lib/sprockets/cached_environment.rb:44:in `load'
# .rvm/gems/ruby-3.1.0/gems/sprockets-4.0.2/lib/sprockets/bundle.rb:27:in `call'
# .rvm/gems/ruby-3.1.0/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:84:in `call_processor'
# .rvm/gems/ruby-3.1.0/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
# .rvm/gems/ruby-3.1.0/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:65:in `reverse_each'
# .rvm/gems/ruby-3.1.0/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:65:in `call_processors'
# .rvm/gems/ruby-3.1.0/gems/sprockets-4.0.2/lib/sprockets/loader.rb:182:in `load_from_unloaded'
# .rvm/gems/ruby-3.1.0/gems/sprockets-4.0.2/lib/sprockets/loader.rb:59:in `block in load'
# .rvm/gems/ruby-3.1.0/gems/sprockets-4.0.2/lib/sprockets/loader.rb:337:in `fetch_asset_from_dependency_cache'
# .rvm/gems/ruby-3.1.0/gems/sprockets-4.0.2/lib/sprockets/loader.rb:43:in `load'
# .rvm/gems/ruby-3.1.0/gems/sprockets-4.0.2/lib/sprockets/cached_environment.rb:44:in `load'
# .rvm/gems/ruby-3.1.0/gems/sprockets-4.0.2/lib/sprockets/base.rb:81:in `find_asset'
# .rvm/gems/ruby-3.1.0/gems/sprockets-4.0.2/lib/sprockets/base.rb:88:in `find_all_linked_assets'
# .rvm/gems/ruby-3.1.0/gems/sprockets-4.0.2/lib/sprockets/manifest.rb:125:in `block (2 levels) in find'
# .rvm/gems/ruby-3.1.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
# .rvm/gems/ruby-3.1.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:47:in `block in synchronize'
# .rvm/gems/ruby-3.1.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:47:in `synchronize'
# .rvm/gems/ruby-3.1.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:47:in `synchronize'
# .rvm/gems/ruby-3.1.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:19:in `execute'
# .rvm/gems/ruby-3.1.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/promise.rb:564:in `block in realize'
# .rvm/gems/ruby-3.1.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:363:in `run_task'
# .rvm/gems/ruby-3.1.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `block (3 levels) in create_worker'
# .rvm/gems/ruby-3.1.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `loop'
# .rvm/gems/ruby-3.1.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `block (2 levels) in create_worker'
# .rvm/gems/ruby-3.1.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `catch'
# .rvm/gems/ruby-3.1.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block in create_worker'
# ------------------
# --- Caused by: ---
# SassC::SyntaxError:
#   Error: Incompatible units: 'rem' and 'px'.
#           on line 1116:37 of ../../../../.rvm/gems/ruby-3.1.0/bundler/gems/rails_admin-ac0a563a0bf9/vendor/assets/stylesheets/rails_admin/bootstrap/_variables.scss
#           from line 11:9 of ../../../../.rvm/gems/ruby-3.1.0/bundler/gems/rails_admin-ac0a563a0bf9/vendor/assets/stylesheets/rails_admin/bootstrap/bootstrap.scss
#           from line 15:9 of ../../../../.rvm/gems/ruby-3.1.0/bundler/gems/rails_admin-ac0a563a0bf9/app/assets/stylesheets/rails_admin/application.scss
#   >> $nav-link-height:                   $font-size-base * $line-height-base + $n
#      ------------------------------------^
#   .rvm/gems/ruby-3.1.0/gems/sassc-2.4.0/lib/sassc/engine.rb:50:in `render'

```

**Comment by mshibuya** [comment]
My guess is that somewhere in your app you have set `$font-size-base` using the `px` unit. Could you try `grep -r`?

**Comment by mshibuya** [comment]
Please reopen on update.
