### ISSUE TITLE
Rails ujs causing problems when it's already initialised in application.js

### ISSUE THREAD

**Issue by estebanz01** [railsadminteam/rails_admin#3484]
**Describe the bug**
When `rails-ujs` is started via `application.js` of main rails app, when I go to `/admin` and go back, the following js error is triggered:

```javascript
Error: rails-ujs has already been loaded!
    start rails-ujs.js:740
    <anonymous> application.js:13
    Webpack 3
        n
        <anonymous>
        <anonymous>
application.js:15:10
```

This is also causing `trix` to being loaded twice as well, generating a bunch of weird errors on the frontend size.

**Reproduction steps**
rails 7 app with activestorage, webpacker and rails admin installed, then this code added in `app/javascript/packs/application.js`:
```javascript
require("@rails/ujs").start()
```

**Expected behavior**
not sure, but I believe `rails-ujs` should only be initialised once, probably on the rails app side.

**Additional context**

- `rails` version: 7.0.1
- `rails_admin` version: 3.0.0.rc3`
- full stack trace (if there's an exception)

**Comment by estebanz01** [comment]
Actually, the problem is not only with rails-ujs, but also with the same javascript libraries loaded both by the main app and the rails admin engine. Not sure how to fix this, tbh.

**Comment by mshibuya** [comment]
Pushed the fix to the new branch `3.0-stable`, could you try?

```ruby
gem 'rails_admin', github: 'railsadminteam/rails_admin', branch: '3.0-stable'
```

Normally the main Rails application and RailsAdmin have independent JavaScript assets, but navigating via Turbo Drive between them didn't clear the loaded JavaScripts, hence this issue.
The fix solves this by moving out from the RailsAdmin with `data: {turbo: 'false'}` to perform the ordinary(non Turbo-Drive) transition, and setting `data: {'turbo-track': 'reload'}` to assets to recover from a situation where users are moving in to RailsAdmin via Turbo Drive.

**Comment by estebanz01** [comment]
I'll give it a shot and report back.

**Comment by estebanz01** [comment]
@mshibuya after moving to `3.0-stable` branch, we got this error:

```ruby
/home/local-user/.rvm/gems/ruby-3.1.0@ark/bundler/gems/rails_admin-e38eb46ffe79/lib/rails_admin/engine.rb:73:in `block in <class:Engine>'
 : uninitialized constant RailsAdmin::Version (NameError)

      RailsAdmin::Version.warn_with_js_version
                ^^^^^^^^^
    from /home/local-user/.rvm/gems/ruby-3.1.0@ark/gems/activesupport-7.0.2.2/lib/active_support/lazy_load_hooks.rb:68:in `block in execute_hook'
    from /home/local-user/.rvm/gems/ruby-3.1.0@ark/gems/activesupport-7.0.2.2/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
    from /home/local-user/.rvm/gems/ruby-3.1.0@ark/gems/activesupport-7.0.2.2/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
    from /home/local-user/.rvm/gems/ruby-3.1.0@ark/gems/activesupport-7.0.2.2/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
    from /home/local-user/.rvm/gems/ruby-3.1.0@ark/gems/activesupport-7.0.2.2/lib/active_support/lazy_load_hooks.rb:51:in `each'
    from /home/local-user/.rvm/gems/ruby-3.1.0@ark/gems/activesupport-7.0.2.2/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
    from /home/local-user/.rvm/gems/ruby-3.1.0@ark/gems/railties-7.0.2.2/lib/rails/application/finisher.rb:85:in `block in <module:Finisher>'
    from /home/local-user/.rvm/gems/ruby-3.1.0@ark/gems/railties-7.0.2.2/lib/rails/initializable.rb:32:in `instance_exec'
    from /home/local-user/.rvm/gems/ruby-3.1.0@ark/gems/railties-7.0.2.2/lib/rails/initializable.rb:32:in `run'
    from /home/local-user/.rvm/gems/ruby-3.1.0@ark/gems/railties-7.0.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
    from /home/local-user/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
    from /home/local-user/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
    from /home/local-user/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
    from /home/local-user/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
    from /home/local-user/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/tsort.rb:347:in `each'
    from /home/local-user/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/tsort.rb:347:in `call'
    from /home/local-user/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
    from /home/local-user/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
    from /home/local-user/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
    from /home/local-user/.rvm/gems/ruby-3.1.0@ark/gems/railties-7.0.2.2/lib/rails/initializable.rb:60:in `run_initializers'
    from /home/local-user/.rvm/gems/ruby-3.1.0@ark/gems/railties-7.0.2.2/lib/rails/application.rb:372:in `initialize!'
    from /home/local-user/Documents/Avlos/ark/app/config/environment.rb:5:in `<top (required)>'
    from config.ru:3:in `require_relative'
    from config.ru:3:in `block in <main>'
    from /home/local-user/.rvm/gems/ruby-3.1.0@ark/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
    from /home/local-user/.rvm/gems/ruby-3.1.0@ark/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
    from /home/local-user/.rvm/gems/ruby-3.1.0@ark/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
    from /home/local-user/.rvm/gems/ruby-3.1.0@ark/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
    from /home/local-user/.rvm/gems/ruby-3.1.0@ark/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
    from /home/local-user/.rvm/gems/ruby-3.1.0@ark/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
    from /home/local-user/.rvm/gems/ruby-3.1.0@ark/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
    from /home/local-user/.rvm/gems/ruby-3.1.0@ark/gems/railties-7.0.2.2/lib/rails/commands/server/server_command.rb:76:in `log_to_stdout'
    from /home/local-user/.rvm/gems/ruby-3.1.0@ark/gems/railties-7.0.2.2/lib/rails/commands/server/server_command.rb:36:in `start'
    from /home/local-user/.rvm/gems/ruby-3.1.0@ark/gems/railties-7.0.2.2/lib/rails/commands/server/server_command.rb:143:in `block in perform'
    from <internal:kernel>:90:in `tap'
    from /home/local-user/.rvm/gems/ruby-3.1.0@ark/gems/railties-7.0.2.2/lib/rails/commands/server/server_command.rb:134:in `perform'
    from /home/local-user/.rvm/gems/ruby-3.1.0@ark/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
    from /home/local-user/.rvm/gems/ruby-3.1.0@ark/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
    from /home/local-user/.rvm/gems/ruby-3.1.0@ark/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
    from /home/local-user/.rvm/gems/ruby-3.1.0@ark/gems/railties-7.0.2.2/lib/rails/command/base.rb:87:in `perform'
    from /home/local-user/.rvm/gems/ruby-3.1.0@ark/gems/railties-7.0.2.2/lib/rails/command.rb:48:in `invoke'
    from /home/local-user/.rvm/gems/ruby-3.1.0@ark/gems/railties-7.0.2.2/lib/rails/commands.rb:18:in `<top (required)>'
    from bin/rails:4:in `require'
    from bin/rails:4:in `<main>'
```

after fixing it by adding `require_relative './version'` to `engine.rb`, it definitely works and the js libraries no longer collide 🥳 .

I'll keep an eye on the fix for the version thing.

**Comment by mshibuya** [comment]
Thanks for confirming, just pushed the fix for the error.
Then closing this!
