### ISSUE TITLE
TypeError in RailsAdmin::Main#index

### ISSUE THREAD

**Issue by ciscolive** [railsadminteam/rails_admin#3494]
**Describe the bug**
TypeError in RailsAdmin::Main#index

visit the site http://127.0.0.1:3000/rails_admin/device_config, but raised no implicit conversion of nil into Integer , please give some advice, thanks !
**Reproduction steps**

Steps to reproduce the issue seen.
```perl
model device_config
class CreateDeviceConfigs < ActiveRecord::Migration[7.0]
  def change
    create_table :device_configs do |t|
      t.inet :ip
      t.string :name
      t.text :content
      t.integer :tag, default: 0
      t.string :flag
      t.string :hash
      t.string :notes

      t.timestamps
      # t.index :hash, unique: true
    end
  end

class CreateDevices < ActiveRecord::Migration[7.0]
  def change
    create_table :devices do |t|
      t.inet :ip, null: false, unique: true
      t.string :name
      t.string :dns, unique: true
      t.text :descr
      t.string :asset_tag
      t.string :uptime
      t.string :contact
      t.string :location
      t.string :layers
      t.string :sn, null: false
      t.string :vendor
      t.string :os
      t.string :os_ver
      t.string :version
      t.string :perl_module
      t.string :supplier
      t.string :contract
      t.string :site_rack
      t.integer :status, default: 0
      t.integer :state, default: 0
      t.string :hw_tag
      t.boolean :monitor, default: false
      # 增加设备生命周期
      t.datetime :date_hw_purchase
      t.datetime :date_hw_install
      t.datetime :date_hw_expiry
      t.datetime :date_hw_decomm
      t.integer :tag, default: 0
      t.string :flag
      t.string :notes
      # 设备相关配置
      t.references :running_config # , foreign_key: { to_table: "credits" }
      t.references :start_config # , foreign_key: { to_table: "credits" }
      t.references :health_check # , foreign_key: { to_table: "credits" }
      t.references :snapshot # , foreign_key: { to_table: "credits" }
      t.integer :ops_level, default: 0

      t.timestamps
      t.index :ip, unique: true
      t.index :sn, unique: true
    end
  end
end

class Device < ApplicationRecord
  has_paper_trail
  # 设备配置信息
  belongs_to :running_config, class_name: "DeviceConfig", optional: true
  belongs_to :start_config, class_name: "DeviceConfig", optional: true
  belongs_to :health_check, class_name: "DeviceConfig", optional: true
  belongs_to :snapshot, class_name: "DeviceConfig", optional: true
end

class DeviceConfig < ApplicationRecord
  has_paper_trail

  # 设备配置信息
  has_one :running_config_device, class_name: "Device", foreign_key: "running_config_id"
  has_one :start_config_device, class_name: "Device", foreign_key: "start_config_id"
  has_one :health_check_device, class_name: "Device", foreign_key: "health_check_id"
  has_one :snapshot_device, class_name: "Device", foreign_key: "snapshot_id"

  enum tag: {
    need_monitor: 0,
    not_required: 1
  }

end
```

**Expected behavior**

**Additional context**

- `rails` version:
- `rails_admin` version:
- full stack trace (if there's an exception)
```ruby
Method:      GET
URL:         /rails_admin/device_config/new
Controller:  rails_admin/main#new
RequestId:   3c870ee8-095e-437c-bbca-9f4f91e6e398
User-Agent:  Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36
Remote IP:   127.0.0.1
Language:    zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7
Server:      careline
Process:     345046

--------------------------------------------------

#<ActionView::Template::Error: no implicit conversion of nil into Integer>


/home/careline/.rvm/gems/ruby-3.1.0/gems/cancancan-3.3.0/lib/cancan/ability/rules.rb:51:in `values_at'
/home/careline/.rvm/gems/ruby-3.1.0/gems/cancancan-3.3.0/lib/cancan/ability/rules.rb:51:in `possible_relevant_rules'
/home/careline/.rvm/gems/ruby-3.1.0/gems/cancancan-3.3.0/lib/cancan/ability/rules.rb:38:in `relevant_rules'
/home/careline/.rvm/gems/ruby-3.1.0/gems/cancancan-3.3.0/lib/cancan/ability/rules.rb:60:in `relevant_rules_for_match'
/home/careline/.rvm/gems/ruby-3.1.0/gems/cancancan-3.3.0/lib/cancan/ability.rb:76:in `block in can?'
/home/careline/.rvm/gems/ruby-3.1.0/gems/cancancan-3.3.0/lib/cancan/ability.rb:79:in `each'
/home/careline/.rvm/gems/ruby-3.1.0/gems/cancancan-3.3.0/lib/cancan/ability.rb:79:in `each'
/home/careline/.rvm/gems/ruby-3.1.0/gems/cancancan-3.3.0/lib/cancan/ability.rb:79:in `each'
/home/careline/.rvm/gems/ruby-3.1.0/gems/cancancan-3.3.0/lib/cancan/ability.rb:79:in `each'
/home/careline/.rvm/gems/ruby-3.1.0/gems/cancancan-3.3.0/lib/cancan/ability.rb:79:in `first'
/home/careline/.rvm/gems/ruby-3.1.0/gems/cancancan-3.3.0/lib/cancan/ability.rb:79:in `can?'
/home/careline/.rvm/gems/ruby-3.1.0/gems/rails_admin-3.0.0.rc3/lib/rails_admin/extensions/cancancan/authorization_adapter.rb:42:in `authorized?'
/home/careline/.rvm/gems/ruby-3.1.0/gems/rails_admin-3.0.0.rc3/lib/rails_admin/config/actions/base.rb:57:in `block in <class:Base>'
/home/careline/.rvm/gems/ruby-3.1.0/gems/rails_admin-3.0.0.rc3/lib/rails_admin/config/configurable.rb:75:in `instance_eval'
/home/careline/.rvm/gems/ruby-3.1.0/gems/rails_admin-3.0.0.rc3/lib/rails_admin/config/configurable.rb:75:in `block in register_instance_option'
/home/careline/.rvm/gems/ruby-3.1.0/gems/rails_admin-3.0.0.rc3/lib/rails_admin/config/configurable.rb:59:in `block in register_instance_option'
/home/careline/.rvm/gems/ruby-3.1.0/gems/rails_admin-3.0.0.rc3/lib/rails_admin/config/actions/base.rb:44:in `block in <class:Base>'
/home/careline/.rvm/gems/ruby-3.1.0/gems/rails_admin-3.0.0.rc3/lib/rails_admin/config/configurable.rb:75:in `instance_eval'
/home/careline/.rvm/gems/ruby-3.1.0/gems/rails_admin-3.0.0.rc3/lib/rails_admin/config/configurable.rb:75:in `block in register_instance_option'
/home/careline/.rvm/gems/ruby-3.1.0/gems/rails_admin-3.0.0.rc3/lib/rails_admin/config/configurable.rb:59:in `block in register_instance_option'
/home/careline/.rvm/gems/ruby-3.1.0/gems/rails_admin-3.0.0.rc3/lib/rails_admin/config/proxyable/proxy.rb:25:in `method_missing'
/home/careline/.rvm/gems/ruby-3.1.0/gems/rails_admin-3.0.0.rc3/lib/rails_admin/config/actions.rb:27:in `select'
/home/careline/.rvm/gems/ruby-3.1.0/gems/rails_admin-3.0.0.rc3/lib/rails_admin/config/actions.rb:27:in `all'
/home/careline/.rvm/gems/ruby-3.1.0/gems/rails_admin-3.0.0.rc3/app/helpers/rails_admin/application_helper.rb:19:in `actions'
/home/careline/.rvm/gems/ruby-3.1.0/gems/rails_admin-3.0.0.rc3/app/helpers/rails_admin/application_helper.rb:158:in `menu_for'
/home/careline/.rvm/gems/ruby-3.1.0/gems/rails_admin-3.0.0.rc3/app/views/layouts/rails_admin/content.html.erb:19:in `__home_careline__rvm_gems_ruby_______gems_rails_admin_______rc__app_views_layouts_rails_admin_content_html_erb__1635383183490622996_63260'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionview-7.0.2.3/lib/action_view/base.rb:244:in `public_send'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionview-7.0.2.3/lib/action_view/base.rb:244:in `_run'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionview-7.0.2.3/lib/action_view/template.rb:157:in `block in render'
/home/careline/.rvm/gems/ruby-3.1.0/gems/activesupport-7.0.2.3/lib/active_support/notifications.rb:206:in `block in instrument'
/home/careline/.rvm/gems/ruby-3.1.0/gems/activesupport-7.0.2.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/home/careline/.rvm/gems/ruby-3.1.0/gems/sentry-rails-5.2.0/lib/sentry/rails/tracing.rb:54:in `instrument'
/home/careline/.rvm/gems/ruby-3.1.0/gems/activesupport-7.0.2.3/lib/active_support/notifications.rb:206:in `instrument'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionview-7.0.2.3/lib/action_view/template.rb:361:in `instrument_render_template'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionview-7.0.2.3/lib/action_view/template.rb:155:in `render'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionview-7.0.2.3/lib/action_view/renderer/template_renderer.rb:65:in `block (2 levels) in render_template'
/home/careline/.rvm/gems/ruby-3.1.0/gems/activesupport-7.0.2.3/lib/active_support/notifications.rb:206:in `block in instrument'
/home/careline/.rvm/gems/ruby-3.1.0/gems/activesupport-7.0.2.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/home/careline/.rvm/gems/ruby-3.1.0/gems/sentry-rails-5.2.0/lib/sentry/rails/tracing.rb:54:in `instrument'
/home/careline/.rvm/gems/ruby-3.1.0/gems/activesupport-7.0.2.3/lib/active_support/notifications.rb:206:in `instrument'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionview-7.0.2.3/lib/action_view/renderer/template_renderer.rb:60:in `block in render_template'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionview-7.0.2.3/lib/action_view/renderer/template_renderer.rb:79:in `render_with_layout'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionview-7.0.2.3/lib/action_view/renderer/template_renderer.rb:59:in `render_template'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionview-7.0.2.3/lib/action_view/renderer/template_renderer.rb:11:in `render'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionview-7.0.2.3/lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionview-7.0.2.3/lib/action_view/renderer/renderer.rb:29:in `render_to_object'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionview-7.0.2.3/lib/action_view/renderer/renderer.rb:22:in `render'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionview-7.0.2.3/lib/action_view/helpers/rendering_helper.rb:38:in `block in render'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionview-7.0.2.3/lib/action_view/base.rb:270:in `in_rendering_context'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionview-7.0.2.3/lib/action_view/helpers/rendering_helper.rb:34:in `render'
/home/careline/.rvm/gems/ruby-3.1.0/gems/rails_admin-3.0.0.rc3/app/views/layouts/rails_admin/application.html.erb:18:in `__home_careline__rvm_gems_ruby_______gems_rails_admin_______rc__app_views_layouts_rails_admin_application_html_erb___169496629089754227_61820'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionview-7.0.2.3/lib/action_view/base.rb:244:in `public_send'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionview-7.0.2.3/lib/action_view/base.rb:244:in `_run'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionview-7.0.2.3/lib/action_view/template.rb:157:in `block in render'
/home/careline/.rvm/gems/ruby-3.1.0/gems/activesupport-7.0.2.3/lib/active_support/notifications.rb:206:in `block in instrument'
/home/careline/.rvm/gems/ruby-3.1.0/gems/activesupport-7.0.2.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/home/careline/.rvm/gems/ruby-3.1.0/gems/sentry-rails-5.2.0/lib/sentry/rails/tracing.rb:54:in `instrument'
/home/careline/.rvm/gems/ruby-3.1.0/gems/activesupport-7.0.2.3/lib/active_support/notifications.rb:206:in `instrument'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionview-7.0.2.3/lib/action_view/template.rb:361:in `instrument_render_template'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionview-7.0.2.3/lib/action_view/template.rb:155:in `render'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionview-7.0.2.3/lib/action_view/renderer/template_renderer.rb:76:in `block in render_with_layout'
/home/careline/.rvm/gems/ruby-3.1.0/gems/activesupport-7.0.2.3/lib/active_support/notifications.rb:206:in `block in instrument'
/home/careline/.rvm/gems/ruby-3.1.0/gems/activesupport-7.0.2.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/home/careline/.rvm/gems/ruby-3.1.0/gems/sentry-rails-5.2.0/lib/sentry/rails/tracing.rb:54:in `instrument'
/home/careline/.rvm/gems/ruby-3.1.0/gems/activesupport-7.0.2.3/lib/active_support/notifications.rb:206:in `instrument'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionview-7.0.2.3/lib/action_view/renderer/template_renderer.rb:74:in `render_with_layout'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionview-7.0.2.3/lib/action_view/renderer/template_renderer.rb:59:in `render_template'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionview-7.0.2.3/lib/action_view/renderer/template_renderer.rb:11:in `render'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionview-7.0.2.3/lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionview-7.0.2.3/lib/action_view/renderer/renderer.rb:29:in `render_to_object'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionview-7.0.2.3/lib/action_view/rendering.rb:117:in `block in _render_template'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionview-7.0.2.3/lib/action_view/base.rb:270:in `in_rendering_context'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionview-7.0.2.3/lib/action_view/rendering.rb:116:in `_render_template'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/action_controller/metal/streaming.rb:216:in `_render_template'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionview-7.0.2.3/lib/action_view/rendering.rb:103:in `render_to_body'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/action_controller/metal/rendering.rb:46:in `render_to_body'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/action_controller/metal/renderers.rb:142:in `render_to_body'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/abstract_controller/rendering.rb:25:in `render'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/action_controller/metal/rendering.rb:30:in `render'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/action_controller/metal/instrumentation.rb:22:in `block (2 levels) in render'
/home/careline/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/benchmark.rb:311:in `realtime'
/home/careline/.rvm/gems/ruby-3.1.0/gems/activesupport-7.0.2.3/lib/active_support/core_ext/benchmark.rb:14:in `ms'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/action_controller/metal/instrumentation.rb:22:in `block in render'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/action_controller/metal/instrumentation.rb:91:in `cleanup_view_runtime'
/home/careline/.rvm/gems/ruby-3.1.0/gems/activerecord-7.0.2.3/lib/active_record/railties/controller_runtime.rb:34:in `cleanup_view_runtime'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/action_controller/metal/instrumentation.rb:21:in `render'
/home/careline/.rvm/gems/ruby-3.1.0/gems/meta-tags-2.16.0/lib/meta_tags/controller_helper.rb:22:in `render'
/home/careline/.rvm/gems/ruby-3.1.0/gems/rails_admin-3.0.0.rc3/lib/rails_admin/config/actions/new.rb:30:in `block (4 levels) in <class:New>'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/action_controller/metal/mime_responds.rb:214:in `respond_to'
/home/careline/.rvm/gems/ruby-3.1.0/gems/rails_admin-3.0.0.rc3/lib/rails_admin/config/actions/new.rb:29:in `block (2 levels) in <class:New>'
/home/careline/.rvm/gems/ruby-3.1.0/gems/rails_admin-3.0.0.rc3/app/controllers/rails_admin/main_controller.rb:36:in `instance_eval'
/home/careline/.rvm/gems/ruby-3.1.0/gems/rails_admin-3.0.0.rc3/app/controllers/rails_admin/main_controller.rb:36:in `action_missing'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/abstract_controller/base.rb:228:in `_handle_action_missing'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/abstract_controller/base.rb:214:in `process_action'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/action_controller/metal/rendering.rb:53:in `process_action'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/abstract_controller/callbacks.rb:234:in `block in process_action'
/home/careline/.rvm/gems/ruby-3.1.0/gems/activesupport-7.0.2.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actiontext-7.0.2.3/lib/action_text/rendering.rb:20:in `with_renderer'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actiontext-7.0.2.3/lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'
/home/careline/.rvm/gems/ruby-3.1.0/gems/activesupport-7.0.2.3/lib/active_support/callbacks.rb:127:in `instance_exec'
/home/careline/.rvm/gems/ruby-3.1.0/gems/activesupport-7.0.2.3/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
/home/careline/.rvm/gems/ruby-3.1.0/gems/activesupport-7.0.2.3/lib/active_support/callbacks.rb:138:in `run_callbacks'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/abstract_controller/callbacks.rb:233:in `process_action'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/action_controller/metal/rescue.rb:22:in `process_action'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'
/home/careline/.rvm/gems/ruby-3.1.0/gems/activesupport-7.0.2.3/lib/active_support/notifications.rb:206:in `block in instrument'
/home/careline/.rvm/gems/ruby-3.1.0/gems/activesupport-7.0.2.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/home/careline/.rvm/gems/ruby-3.1.0/gems/sentry-rails-5.2.0/lib/sentry/rails/tracing.rb:54:in `instrument'
/home/careline/.rvm/gems/ruby-3.1.0/gems/activesupport-7.0.2.3/lib/active_support/notifications.rb:206:in `instrument'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/action_controller/metal/instrumentation.rb:66:in `process_action'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
/home/careline/.rvm/gems/ruby-3.1.0/gems/activerecord-7.0.2.3/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/abstract_controller/base.rb:151:in `process'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionview-7.0.2.3/lib/action_view/rendering.rb:39:in `process'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/action_controller/metal.rb:188:in `dispatch'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/action_controller/metal.rb:251:in `dispatch'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/routing/route_set.rb:32:in `serve'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/journey/router.rb:50:in `block in serve'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/journey/router.rb:32:in `each'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/journey/router.rb:32:in `serve'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/routing/route_set.rb:850:in `call'
/home/careline/.rvm/gems/ruby-3.1.0/gems/railties-7.0.2.3/lib/rails/engine.rb:530:in `call'
/home/careline/.rvm/gems/ruby-3.1.0/gems/railties-7.0.2.3/lib/rails/railtie.rb:224:in `public_send'
/home/careline/.rvm/gems/ruby-3.1.0/gems/railties-7.0.2.3/lib/rails/railtie.rb:224:in `method_missing'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/routing/mapper.rb:48:in `serve'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/journey/router.rb:50:in `block in serve'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/journey/router.rb:32:in `each'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/journey/router.rb:32:in `serve'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/routing/route_set.rb:850:in `call'
/home/careline/.rvm/gems/ruby-3.1.0/gems/http_accept_language-2.1.1/lib/http_accept_language/middleware.rb:14:in `call'
/home/careline/.rvm/gems/ruby-3.1.0/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'
/home/careline/.rvm/gems/ruby-3.1.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'
/home/careline/.rvm/gems/ruby-3.1.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'
/home/careline/.rvm/gems/ruby-3.1.0/gems/exception-track-1.3.0/lib/exception_notification/rack.rb:49:in `call'
/home/careline/.rvm/gems/ruby-3.1.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
/home/careline/.rvm/gems/ruby-3.1.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
/home/careline/.rvm/gems/ruby-3.1.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:27:in `call'
/home/careline/.rvm/gems/ruby-3.1.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/http/permissions_policy.rb:22:in `call'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
/home/careline/.rvm/gems/ruby-3.1.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
/home/careline/.rvm/gems/ruby-3.1.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/middleware/cookies.rb:693:in `call'
/home/careline/.rvm/gems/ruby-3.1.0/gems/activerecord-7.0.2.3/lib/active_record/migration.rb:603:in `call'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
/home/careline/.rvm/gems/ruby-3.1.0/gems/activesupport-7.0.2.3/lib/active_support/callbacks.rb:99:in `run_callbacks'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
/home/careline/.rvm/gems/ruby-3.1.0/gems/sentry-rails-5.2.0/lib/sentry/rails/rescued_exception_interceptor.rb:12:in `call'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
/home/careline/.rvm/gems/ruby-3.1.0/gems/web-console-4.2.0/lib/web_console/middleware.rb:132:in `call_app'
/home/careline/.rvm/gems/ruby-3.1.0/gems/web-console-4.2.0/lib/web_console/middleware.rb:28:in `block in call'
/home/careline/.rvm/gems/ruby-3.1.0/gems/web-console-4.2.0/lib/web_console/middleware.rb:17:in `catch'
/home/careline/.rvm/gems/ruby-3.1.0/gems/web-console-4.2.0/lib/web_console/middleware.rb:17:in `call'
/home/careline/.rvm/gems/ruby-3.1.0/gems/sentry-ruby-core-5.2.0/lib/sentry/rack/capture_exceptions.rb:26:in `block (2 levels) in call'
/home/careline/.rvm/gems/ruby-3.1.0/gems/sentry-ruby-core-5.2.0/lib/sentry/hub.rb:199:in `with_session_tracking'
/home/careline/.rvm/gems/ruby-3.1.0/gems/sentry-ruby-core-5.2.0/lib/sentry-ruby.rb:342:in `with_session_tracking'
/home/careline/.rvm/gems/ruby-3.1.0/gems/sentry-ruby-core-5.2.0/lib/sentry/rack/capture_exceptions.rb:17:in `block in call'
/home/careline/.rvm/gems/ruby-3.1.0/gems/sentry-ruby-core-5.2.0/lib/sentry/hub.rb:59:in `with_scope'
/home/careline/.rvm/gems/ruby-3.1.0/gems/sentry-ruby-core-5.2.0/lib/sentry-ruby.rb:322:in `with_scope'
/home/careline/.rvm/gems/ruby-3.1.0/gems/sentry-ruby-core-5.2.0/lib/sentry/rack/capture_exceptions.rb:16:in `call'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
/home/careline/.rvm/gems/ruby-3.1.0/gems/railties-7.0.2.3/lib/rails/rack/logger.rb:36:in `call_app'
/home/careline/.rvm/gems/ruby-3.1.0/gems/railties-7.0.2.3/lib/rails/rack/logger.rb:25:in `block in call'
/home/careline/.rvm/gems/ruby-3.1.0/gems/activesupport-7.0.2.3/lib/active_support/tagged_logging.rb:99:in `block in tagged'
/home/careline/.rvm/gems/ruby-3.1.0/gems/activesupport-7.0.2.3/lib/active_support/tagged_logging.rb:37:in `tagged'
/home/careline/.rvm/gems/ruby-3.1.0/gems/activesupport-7.0.2.3/lib/active_support/tagged_logging.rb:99:in `tagged'
/home/careline/.rvm/gems/ruby-3.1.0/gems/railties-7.0.2.3/lib/rails/rack/logger.rb:25:in `call'
/home/careline/.rvm/gems/ruby-3.1.0/gems/sprockets-rails-3.4.2/lib/sprockets/rails/quiet_assets.rb:13:in `call'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
/home/careline/.rvm/gems/ruby-3.1.0/gems/request_store-1.5.1/lib/request_store/middleware.rb:19:in `call'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/middleware/request_id.rb:26:in `call'
/home/careline/.rvm/gems/ruby-3.1.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
/home/careline/.rvm/gems/ruby-3.1.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
/home/careline/.rvm/gems/ruby-3.1.0/gems/activesupport-7.0.2.3/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/middleware/server_timing.rb:20:in `call'
/home/careline/.rvm/gems/ruby-3.1.0/gems/rails_performance-1.0.1/lib/rails_performance/rails/middleware.rb:42:in `call!'
/home/careline/.rvm/gems/ruby-3.1.0/gems/rails_performance-1.0.1/lib/rails_performance/rails/middleware.rb:38:in `call'
/home/careline/.rvm/gems/ruby-3.1.0/gems/rails_performance-1.0.1/lib/rails_performance/rails/middleware.rb:17:in `call!'
/home/careline/.rvm/gems/ruby-3.1.0/gems/rails_performance-1.0.1/lib/rails_performance/rails/middleware.rb:9:in `call'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/middleware/static.rb:23:in `call'
/home/careline/.rvm/gems/ruby-3.1.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
/home/careline/.rvm/gems/ruby-3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/middleware/host_authorization.rb:137:in `call'
/home/careline/.rvm/gems/ruby-3.1.0/gems/railties-7.0.2.3/lib/rails/engine.rb:530:in `call'
/home/careline/.rvm/gems/ruby-3.1.0/gems/puma-5.6.2/lib/puma/configuration.rb:252:in `call'
/home/careline/.rvm/gems/ruby-3.1.0/gems/puma-5.6.2/lib/puma/request.rb:77:in `block in handle_request'
/home/careline/.rvm/gems/ruby-3.1.0/gems/puma-5.6.2/lib/puma/thread_pool.rb:340:in `with_force_shutdown'
/home/careline/.rvm/gems/ruby-3.1.0/gems/puma-5.6.2/lib/puma/request.rb:76:in `handle_request'
/home/careline/.rvm/gems/ruby-3.1.0/gems/puma-5.6.2/lib/puma/server.rb:441:in `process_client'
/home/careline/.rvm/gems/ruby-3.1.0/gems/puma-5.6.2/lib/puma/thread_pool.rb:147:in `block in spawn_thread'
```

**Comment by ciscolive** [comment]
It's ok now, not rails_admin bug
