### ISSUE TITLE
How to get rid of scss via sprockets when using webpacker

### ISSUE THREAD

**Issue by bb** [railsadminteam/rails_admin#3502]
**Describe the bug**
I upgraded rails_admin from 2.x to 3.x and switched to webpacker and it's working fine without sprockets. However, I also use https://github.com/ankane/blazer which still uses sprockets-rails (but not sassc-rails).
However, when I add sprockets-rails back to my application (to make blazer work again), I also need to manually add sassc-rails because even though rails_admin is configured to use webpacker, sprockets-rails tries to compile rails_admin's scss files and fails without it.

**Reproduction steps**
```ruby
RailsAdmin.config do |config|
  config.asset_source = :webpacker
...
```
Gemfile:
```ruby
gem "sprockets-rails"
# gem "sassc-rails"
```
(note that sassc-rails is commented out here. When removing `# `, it will work.)

**Expected behavior**
rails_admin's files should be ignored by sprockets-rails if rails_admin is configured for webpacker

**Additional context**

- `rails` version: 7.0.2.3
- `rails_admin` version: 3.0.0
- `rails_admin` npm package version: 3.0.0
- full stack trace (if there's an exception)
```
rake aborted!
LoadError: cannot load such file -- sassc
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:27:in `require'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/sprockets-4.0.3/lib/sprockets/autoload/sassc.rb:2:in `<main>'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/sprockets-4.0.3/lib/sprockets/sassc_processor.rb:42:in `initialize'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/sprockets-4.0.3/lib/sprockets/sassc_processor.rb:27:in `new'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/sprockets-4.0.3/lib/sprockets/sassc_processor.rb:27:in `instance'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/sprockets-4.0.3/lib/sprockets/sassc_processor.rb:31:in `call'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/sprockets-4.0.3/lib/sprockets/processor_utils.rb:84:in `call_processor'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/sprockets-4.0.3/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/sprockets-4.0.3/lib/sprockets/processor_utils.rb:65:in `reverse_each'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/sprockets-4.0.3/lib/sprockets/processor_utils.rb:65:in `call_processors'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/sprockets-4.0.3/lib/sprockets/processor_utils.rb:22:in `block in <class:CompositeProcessor>'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/sprockets-4.0.3/lib/sprockets/processor_utils.rb:33:in `call'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/sprockets-4.0.3/lib/sprockets/processor_utils.rb:84:in `call_processor'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/sprockets-4.0.3/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/sprockets-4.0.3/lib/sprockets/processor_utils.rb:65:in `reverse_each'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/sprockets-4.0.3/lib/sprockets/processor_utils.rb:65:in `call_processors'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/sprockets-4.0.3/lib/sprockets/loader.rb:182:in `load_from_unloaded'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/sprockets-4.0.3/lib/sprockets/loader.rb:59:in `block in load'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/sprockets-4.0.3/lib/sprockets/loader.rb:337:in `fetch_asset_from_dependency_cache'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/sprockets-4.0.3/lib/sprockets/loader.rb:43:in `load'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/sprockets-4.0.3/lib/sprockets/cached_environment.rb:44:in `load'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/sprockets-4.0.3/lib/sprockets/bundle.rb:27:in `call'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/sprockets-4.0.3/lib/sprockets/processor_utils.rb:84:in `call_processor'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/sprockets-4.0.3/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/sprockets-4.0.3/lib/sprockets/processor_utils.rb:65:in `reverse_each'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/sprockets-4.0.3/lib/sprockets/processor_utils.rb:65:in `call_processors'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/sprockets-4.0.3/lib/sprockets/loader.rb:182:in `load_from_unloaded'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/sprockets-4.0.3/lib/sprockets/loader.rb:59:in `block in load'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/sprockets-4.0.3/lib/sprockets/loader.rb:337:in `fetch_asset_from_dependency_cache'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/sprockets-4.0.3/lib/sprockets/loader.rb:43:in `load'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/sprockets-4.0.3/lib/sprockets/cached_environment.rb:44:in `load'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/sprockets-4.0.3/lib/sprockets/base.rb:81:in `find_asset'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/sprockets-4.0.3/lib/sprockets/base.rb:88:in `find_all_linked_assets'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/sprockets-4.0.3/lib/sprockets/manifest.rb:125:in `each'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/sprockets-4.0.3/lib/sprockets/manifest.rb:125:in `to_a'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/sprockets-4.0.3/lib/sprockets/manifest.rb:125:in `block (2 levels) in find'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:47:in `block in synchronize'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:47:in `synchronize'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:47:in `synchronize'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:22:in `execute'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/promise.rb:564:in `block in realize'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/immediate_executor.rb:29:in `post'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/promise.rb:563:in `realize'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/promise.rb:250:in `execute'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/promise.rb:297:in `execute'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/sprockets-4.0.3/lib/sprockets/manifest.rb:124:in `block in find'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/sprockets-4.0.3/lib/sprockets/manifest.rb:123:in `map'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/sprockets-4.0.3/lib/sprockets/manifest.rb:123:in `find'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/sprockets-4.0.3/lib/sprockets/manifest.rb:170:in `compile'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/sprockets-rails-3.4.2/lib/sprockets/rails/task.rb:67:in `block (3 levels) in define'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/sprockets-4.0.3/lib/rake/sprocketstask.rb:148:in `with_logger'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/sprockets-rails-3.4.2/lib/sprockets/rails/task.rb:66:in `block (2 levels) in define'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/airbrake-13.0.0/lib/airbrake/rake.rb:17:in `execute'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/bundler-2.3.4/lib/bundler/cli/exec.rb:58:in `load'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/bundler-2.3.4/lib/bundler/cli/exec.rb:58:in `kernel_load'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/bundler-2.3.4/lib/bundler/cli/exec.rb:23:in `run'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/bundler-2.3.4/lib/bundler/cli.rb:484:in `exec'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/bundler-2.3.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/bundler-2.3.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/bundler-2.3.4/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/bundler-2.3.4/lib/bundler/cli.rb:31:in `dispatch'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/bundler-2.3.4/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/bundler-2.3.4/lib/bundler/cli.rb:25:in `start'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/bundler-2.3.4/exe/bundle:48:in `block in <top (required)>'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/bundler-2.3.4/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
/home/app/webapp/vendor/bundle/ruby/3.0.0/gems/bundler-2.3.4/exe/bundle:36:in `<top (required)>'
/usr/local/rvm/rubies/ruby-3.0.3/bin/bundle:25:in `load'
/usr/local/rvm/rubies/ruby-3.0.3/bin/bundle:25:in `<main>'
/usr/local/rvm/gems/ruby-3.0.3/bin/ruby_executable_hooks:22:in `eval'
/usr/local/rvm/gems/ruby-3.0.3/bin/ruby_executable_hooks:22:in `<main>'
Tasks: TOP => assets:precompile
```

**Comment by mshibuya** [comment]
Would mind trying this suggestion?
https://github.com/railsadminteam/rails_admin/issues/3536#issuecomment-1179498926

**Comment by mshibuya** [comment]
Stale.
