### ISSUE TITLE
How to use with ActsAsTenant?

### ISSUE THREAD

**Issue by philsmy** [railsadminteam/rails_admin#3523]
**Describe the bug**
Install `rails_admin` into a Rails 7 app (that uses `bootstrap` so it is not using `imagemap`) and attempt to hit the base admin URL (eg `/admin`).
Get a stack trace:
```
ActsAsTenant::Errors::NoTenantSet in RailsAdmin::MainController#dashboard

[acts_as_tenant (0.5.1) lib/acts_as_tenant/model_extensions.rb:20:in `block in acts_as_tenant'](https://postwrangler.ngrok.io/pwadmin#)
[activerecord (7.0.2.3) lib/active_record/scoping/default.rb:157:in `instance_exec'](https://postwrangler.ngrok.io/pwadmin#)
[activerecord (7.0.2.3) lib/active_record/scoping/default.rb:157:in `block (2 levels) in build_default_scope'](https://postwrangler.ngrok.io/pwadmin#)
[activerecord (7.0.2.3) lib/active_record/scoping/default.rb:153:in `each'](https://postwrangler.ngrok.io/pwadmin#)
[activerecord (7.0.2.3) lib/active_record/scoping/default.rb:153:in `inject'](https://postwrangler.ngrok.io/pwadmin#)
[activerecord (7.0.2.3) lib/active_record/scoping/default.rb:153:in `block in build_default_scope'](https://postwrangler.ngrok.io/pwadmin#)
[activerecord (7.0.2.3) lib/active_record/scoping/default.rb:189:in `evaluate_default_scope'](https://postwrangler.ngrok.io/pwadmin#)
[activerecord (7.0.2.3) lib/active_record/scoping/default.rb:152:in `build_default_scope'](https://postwrangler.ngrok.io/pwadmin#)
[activerecord (7.0.2.3) lib/active_record/scoping/named.rb:46:in `default_scoped'](https://postwrangler.ngrok.io/pwadmin#)
[activerecord (7.0.2.3) lib/active_record/scoping/named.rb:32:in `all'](https://postwrangler.ngrok.io/pwadmin#)
[rails_admin (3.0.0) lib/rails_admin/adapters/active_record.rb:23:in `scoped'](https://postwrangler.ngrok.io/pwadmin#)
[rails_admin (3.0.0) lib/rails_admin/adapters/active_record.rb:31:in `all'](https://postwrangler.ngrok.io/pwadmin#)
[rails_admin (3.0.0) lib/rails_admin/adapters/active_record.rb:43:in `count'](https://postwrangler.ngrok.io/pwadmin#)
[rails_admin (3.0.0) lib/rails_admin/config/actions/dashboard.rb:31:in `block (3 levels) in <class:Dashboard>'](https://postwrangler.ngrok.io/pwadmin#)
[rails_admin (3.0.0) lib/rails_admin/config/actions/dashboard.rb:29:in `each'](https://postwrangler.ngrok.io/pwadmin#)
[rails_admin (3.0.0) lib/rails_admin/config/actions/dashboard.rb:29:in `block (2 levels) in <class:Dashboard>'](https://postwrangler.ngrok.io/pwadmin#)
[rails_admin (3.0.0) app/controllers/rails_admin/main_controller.rb:36:in `instance_eval'](https://postwrangler.ngrok.io/pwadmin#)
[rails_admin (3.0.0) app/controllers/rails_admin/main_controller.rb:36:in `action_missing'](https://postwrangler.ngrok.io/pwadmin#)
```

**Additional context**

- `rails` version: 7.0.3
- `rails_admin` version: 3.0.0

**Comment by philsmy** [comment]
Seems this is not a RailsAdmin issue, but an ActsAsTenant one.
