### ISSUE TITLE
importmap-rails download error

### ISSUE THREAD

**Issue by nulty** [railsadminteam/rails_admin#3626]
**Describe the bug**
When using `bin/importmap pin rails_admin --download`, an error is thrown. See below for full stack trace.

**Reproduction steps**
Steps to reproduce the issue seen.
 - `rails new rails_admin_repo -j importmaps`
 - `cd rails_admin_repo`
 - `bundle add rails_admin`
 - `bin/importmap pin rails_admin --download`

**Expected behavior**
I expect the jquery-ui files to each be downloaded and saved to the vendor directory.

**Additional context**

- `rails` version: 7.0.4.3
- `rails_admin` version: 3.1.2
- `rails_admin` npm package version: 3.1.2
- full stack trace (if there's an exception)

```
Pinning "rails_admin" to vendor/javascript/rails_admin.js via download from https://ga.jspm.io/npm:rails_admin@3.1.2/src/rails_admin/base.js
Pinning "@hotwired/turbo" to vendor/javascript/@hotwired/turbo.js via download from https://ga.jspm.io/npm:@hotwired/turbo@7.3.0/dist/turbo.es2017-esm.js
Pinning "@hotwired/turbo-rails" to vendor/javascript/@hotwired/turbo-rails.js via download from https://ga.jspm.io/npm:@hotwired/turbo-rails@7.3.0/app/javascript/turbo/index.js
Pinning "@popperjs/core" to vendor/javascript/@popperjs/core.js via download from https://ga.jspm.io/npm:@popperjs/core@2.11.7/lib/index.js
Pinning "@rails/actioncable/src" to vendor/javascript/@rails/actioncable/src.js via download from https://ga.jspm.io/npm:@rails/actioncable@7.0.4/src/index.js
Pinning "@rails/ujs" to vendor/javascript/@rails/ujs.js via download from https://ga.jspm.io/npm:@rails/ujs@6.1.7/lib/assets/compiled/rails-ujs.js
Pinning "bootstrap" to vendor/javascript/bootstrap.js via download from https://ga.jspm.io/npm:bootstrap@5.2.3/dist/js/bootstrap.esm.js
Pinning "flatpickr" to vendor/javascript/flatpickr.js via download from https://ga.jspm.io/npm:flatpickr@4.6.13/dist/esm/index.js
Pinning "jquery" to vendor/javascript/jquery.js via download from https://ga.jspm.io/npm:jquery@3.7.0/dist/jquery.js
Pinning "jquery-ui/ui/" to vendor/javascript/jquery-ui/ui/.js via download from https://ga.jspm.io/npm:jquery-ui@1.13.2/ui/
/$HOME/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/importmap-rails-1.1.5/lib/importmap/packager.rb:81:in `handle_failure_response': Unexpected response code (404) (Importmap::Packager::HTTPError)
        from /$HOME/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/importmap-rails-1.1.5/lib/importmap/packager.rb:119:in `download_package_file'
        from /$HOME/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/importmap-rails-1.1.5/lib/importmap/packager.rb:58:in `download'
        from /$HOME/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/importmap-rails-1.1.5/lib/importmap/commands.rb:21:in `block in pin'
        from /$HOME/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/importmap-rails-1.1.5/lib/importmap/commands.rb:18:in `each'
        from /$HOME/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/importmap-rails-1.1.5/lib/importmap/commands.rb:18:in `pin'
        from /$HOME/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from /$HOME/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /$HOME/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        from /$HOME/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
        from /$HOME/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/importmap-rails-1.1.5/lib/importmap/commands.rb:142:in `<main>'
        from <internal:/$HOME/.asdf/installs/ruby/3.2.1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/$HOME/.asdf/installs/ruby/3.2.1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /$HOME/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /$HOME/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.8/lib/zeitwerk/kernel.rb:38:in `require' from bin/importmap:4:in `<main>'
```

My understanding is that `importmap-rails` makes a request to jspm.io for the import maps for the library. The service returns an invalid(?) importmap for `jquery-ui`

```
[1] pry(#<Importmap::Packager>)> JSON.parse(response.body).dig("map", "imports")
=> {"rails_admin"=>"https://ga.jspm.io/npm:rails_admin@3.1.2/src/rails_admin/base.js",
 "@hotwired/turbo"=>"https://ga.jspm.io/npm:@hotwired/turbo@7.3.0/dist/turbo.es2017-esm.js",
 "@hotwired/turbo-rails"=>"https://ga.jspm.io/npm:@hotwired/turbo-rails@7.3.0/app/javascript/turbo/index.js",
 "@popperjs/core"=>"https://ga.jspm.io/npm:@popperjs/core@2.11.7/lib/index.js",
 "@rails/actioncable/src"=>"https://ga.jspm.io/npm:@rails/actioncable@7.0.4/src/index.js",
 "@rails/ujs"=>"https://ga.jspm.io/npm:@rails/ujs@6.1.7/lib/assets/compiled/rails-ujs.js",
 "bootstrap"=>"https://ga.jspm.io/npm:bootstrap@5.2.3/dist/js/bootstrap.esm.js",
 "flatpickr"=>"https://ga.jspm.io/npm:flatpickr@4.6.13/dist/esm/index.js",
 "jquery"=>"https://ga.jspm.io/npm:jquery@3.7.0/dist/jquery.js",
 "jquery-ui/ui/"=>"https://ga.jspm.io/npm:jquery-ui@1.13.2/ui/"}
```

`"jquery-ui/ui/"=>"https://ga.jspm.io/npm:jquery-ui@1.13.2/ui/"` this line cannot be resolved. I'm guessing each of the jquery-ui library components should be returned in this json?

This is where importmaps is attempting to download the "file" https://github.com/rails/importmap-rails/blob/main/lib/importmap/packager.rb#LL57C23-L57C23

Is it that rails_admin could be packaged in such a way that the import maps returned are downloadable?

**Comment by costa** [comment]
More than 2 years later, rails_admin setup is still a pain... Why?..

**Comment by 3v0k4** [comment]
For reference, this works:

```ruby
# ...
pin "jquery-ui", to: "https://ga.jspm.io/npm:jquery-ui@1.13.3/dist/jquery-ui.js"
pin "jquery-ui/ui/version.js", to: "https://ga.jspm.io/npm:jquery-ui@1.13.3/ui/version.js"
pin "jquery-ui/ui/keycode.js", to: "https://ga.jspm.io/npm:jquery-ui@1.13.3/ui/keycode.js"
pin "jquery-ui/ui/position.js", to: "https://ga.jspm.io/npm:jquery-ui@1.13.3/ui/position.js"
pin "jquery-ui/ui/safe-active-element.js", to: "https://ga.jspm.io/npm:jquery-ui@1.13.3/ui/safe-active-element.js"
pin "jquery-ui/ui/data.js", to: "https://ga.jspm.io/npm:jquery-ui@1.13.3/ui/data.js"
pin "jquery-ui/ui/ie.js", to: "https://ga.jspm.io/npm:jquery-ui@1.13.3/ui/ie.js"
pin "jquery-ui/ui/scroll-parent.js", to: "https://ga.jspm.io/npm:jquery-ui@1.13.3/ui/scroll-parent.js"
pin "jquery-ui/ui/unique-id.js", to: "https://ga.jspm.io/npm:jquery-ui@1.13.3/ui/unique-id.js"
pin "jquery-ui/ui/widget.js", to: "https://ga.jspm.io/npm:jquery-ui@1.13.3/ui/widget.js"
pin "jquery-ui/ui/widgets/menu.js", to: "https://ga.jspm.io/npm:jquery-ui@1.13.3/ui/widgets/menu.js"
pin "jquery-ui/ui/widgets/mouse.js", to: "https://ga.jspm.io/npm:jquery-ui@1.13.3/ui/widgets/mouse.js"
pin "jquery-ui/ui/widgets/autocomplete.js", to: "https://ga.jspm.io/npm:jquery-ui@1.13.3/ui/widgets/autocomplete.js"
pin "jquery-ui/ui/effect.js", to: "https://ga.jspm.io/npm:jquery-ui@1.13.3/ui/effect.js"
pin "jquery-ui/ui/widgets/sortable.js", to: "https://ga.jspm.io/npm:jquery-ui@1.13.3/ui/widgets/sortable.js"
```

**Comment by 3v0k4** [comment]
Just to be clear, I'm not suggesting what I posted is a (good) solution.

@costa what do you mean with "self-contained?" Maybe I can help since I have `rails_admin` running with `propshaft` and `importmap-rails` with no scss.

**Comment by costa** [comment]
@3v0k4 Thank you for your response and for the article. I'm not a big client-side guy myself, and my modest needs have always been satisfied either way -- while deps are a different story, I have not myself made any client-side packages, so, as a user, I'm not sure what is being improved or not. I just see that the very basic rails_admin integration makes me work, and I don't like it. If you care to supply propshaft+importmap (not just importmap+CDN) solution for rails_admin, that'll be grand.

**Comment by costa** [comment]
@3v0k4 Thanks, isn't this the same solution we've already discussed here https://github.com/railsadminteam/rails_admin/issues/3626#issuecomment-3065020603 ?

**Comment by 3v0k4** [comment]
@costa You asked me to share my configuration, that's what I did 🙂 Please refer to the docs on how to use `impotmaps-rails`: https://github.com/rails/importmap-rails

**Comment by costa** [comment]
@3v0k4 again, thank you for your response, I really appreciate your help. So, I learnt about "vendoring" importmap "pins" and while this seems possible... well, I'm sorry, I still fail to see how referencing npm packages in such an unnatural way -- and then having to deal with vendor files -- is better than "my" current solution with webpack: I've published https://github.com/costa/benderplate.com ahead of a supporting blog post of mine for you. Cheers!

**Comment by mshibuya** [comment]
#3751 removes the importmap path entirely, so this no longer applies as of master, shipping in 4.0.

The problem itself was real and not something we could fix from here: jspm resolves `jquery-ui` to a directory mapping (`"jquery-ui/ui/" => ".../jquery-ui@1.13.2/ui/"`), and `importmap-rails --download` has no way to fetch a directory. Pinning RailsAdmin's dependency tree meant pinning a dozen packages whose published shapes we do not control, and that turned out to be the source of most of the asset issues in this tracker.

RailsAdmin now ships a prebuilt `rails_admin.js` / `rails_admin.css` inside the gem. Propshaft and Sprockets serve them straight off the asset path — no pinning, no `--download`, no Node. Your application's own importmap is untouched; RailsAdmin simply no longer takes part in it.

See [docs/asset-delivery.md](https://github.com/railsadminteam/rails_admin/blob/master/docs/asset-delivery.md).
